superdesk/web-publisher

README.md, docker-compose.yml, docker/php-fpm/Dockerfile, docker/php-fpm/docker-entrypoint.sh
- Installs composer dependencies automatically
- Chowns all command by user on each run
- Also makes a volume in php-fpm container with web dir
=>  Updates docker with entrypoint script setup

.travis.yml
for php nightly and hhvm tests are allowed to fail
=> added hhvm support in travis

.gitignore, README.md, docker-compose.yml, docker/php-fpm/Dockerfile, docker/php-fpm/docker-entrypoint.sh
- Adds postgres container
- Updates README how to configure properly when using docker
=> Updates docker compose to work with postgres

app/config/services.yml, composer.json, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/phone/views/index.html.twig, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/views/article.html.twig, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/views/base.html.twig, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/views/index.html.twig
| New feature?  | yes
| Fixed tickets | no
require php >= 5.5.11, add bootstrap to theme, improve index and article templates
=> [Themes] improve DefaultTheme

README.md, app/AppKernel.php, app/config/config.yml, composer.json, composer.lock, src/SWP/Bundle/MultiTenancyBundle/EventListener/TenantableListener.php, src/SWP/Bundle/MultiTenancyBundle/Resources/config/services.yml, src/SWP/Bundle/WebRendererBundle/EventListener/ActiveThemeListener.php, src/SWP/Bundle/WebRendererBundle/Resources/config/services.yml, src/SWP/Bundle/WebRendererBundle/Tests/Controller/ContentControllerTest.php, src/SWP/Bundle/WebRendererBundle/Tests/Controller/DefaultControllerTest.php
| New feature?  | yes
| Tests pass?   | no
| Fixed tickets | no
=> upgrade sylius/theme-bundle, upgrade project to Symfony2.8 again

app/config/config.yml, app/config/parameters.yml.dist
| Fixed tickets | [SWP-130](https://dev.sourcefabric.org/browse/SWP-130)
=> SWP-130 - Attempt to query the database during the installation

src/SWP/Bundle/ContentBundle/Controller/RoutesController.php, src/SWP/Bundle/TemplateEngineBundle/Resources/config/doctrine/Container.orm.yml
| Tests pass?   | no
| Fixed tickets | [SWP-138](https://dev.sourcefabric.org/browse/SWP-138)
Update your schema with ```php app/console doctrine:cache:clear-metadata && php app/console doctrine:schema:update --force```
=> [SWP-138] container unique name

src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/dev/tenant.yml, src/SWP/Bundle/MultiTenancyBundle/composer.json, src/SWP/Bundle/MultiTenancyBundle/spec/DependencyInjection/Compiler/RegisterTenantFactoryCompilerPassSpec.php
=> [FixturesBundle][MultiTenancy] set default theme, added twig as a dependency

src/SWP/Bundle/MultiTenancyBundle/DependencyInjection/Configuration.php, src/SWP/Bundle/MultiTenancyBundle/Tests/Command/CreateTenantCommandTest.php, src/SWP/Bundle/MultiTenancyBundle/Tests/DependencyInjection/Compiler/RegisterTenantFactoryCompilerPassTest.php, src/SWP/Bundle/MultiTenancyBundle/spec/DependencyInjection/Compiler/RegisterTenantFactoryCompilerPassSpec.php, src/SWP/Bundle/MultiTenancyBundle/spec/Twig/MultiTenancyExtensionSpec.php, src/SWP/Component/MultiTenancy/spec/Factory/TenantFactorySpec.php
=> [MultiTenancy] dont use ::class, supported in php >=5.5

LICENSE.md, PULL_REQUEST_TEMPLATE.md, src/SWP/Bundle/MultiTenancyBundle/LICENSE.md, src/SWP/Component/Common/LICENSE.md, src/SWP/Component/MultiTenancy/LICENSE.md
| Bug fix?      | [no]
| Fixed tickets | [SWP-140]
=> Update code license and pull request template to AGPLv3

docs/_templates_system/containers_and_widgets.rst, docs/_templates_system/templates.rst, docs/components/index.rst, docs/conf.py, docs/contributing/code/license.rst, docs/contributing/code/standards.rst, docs/contributing/documentation/license.rst, docs/contributing/documentation/translations.rst, docs/fixtures.rst, docs/index.rst, docs/templates_caching.rst, docs/templates_system.rst, docs/themes.rst
=> SWP-27 Documentation improvements

src/SWP/Bundle/BridgeBundle/.codeclimate.yml, src/SWP/Bundle/BridgeBundle/.gitignore, src/SWP/Bundle/BridgeBundle/.scrutinizer.yml, src/SWP/Bundle/BridgeBundle/.travis.yml
=> [BridgeBundle] added configuration files

src/SWP/Bundle/TemplateEngineBundle/EventSubscriber/HttpCacheSubscriber.php, src/SWP/Bundle/WebRendererBundle/Enhancer/RouteEnhancer.php
| BC breaks?    |no
| Fixed tickets | no
=> add missing namespace, add required parameter to loader function call

README.md
| Bug fix?      | [no]
| Fixed tickets | [SWP-197]
Added instructions about fixtures to readme
=> Changes to readme file to give instructions about loading fixtures

src/SWP/Bundle/FixturesBundle/Command/ThemeSetupCommand.php
| Bug fix?      | [yes]
| Fixed tickets | []
=> Fixed error in theme setup command

app/Resources/meta/article.yml
=> SWP-215 - Expose article meta 'publishedAt'

app/Resources/meta/article.yml
=> SWP-224 - Expose article meta 'createdAt' and 'updatedAt'

src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Tests/ArticleLoaderTest.php
| Bug fix?      | [yes]
| Fixed tickets | [SWP-236]
=> Fix of gimmelist block in twig with limit, offset and order by parameters

src/SWP/Bundle/BridgeBundle/.travis.yml, src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/StorageBundle/.travis.yml, src/SWP/Bundle/StorageBundle/README.md, src/SWP/Component/Bridge/README.md, src/SWP/Component/Common/README.md, src/SWP/Component/Storage/README.md
=> readme fixes and travis

composer.json, composer.lock, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/AbstractOverridePass.php, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideThemeAssetsInstallerPass.php, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideThemeFactoryPass.php, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideThemePathResolverPass.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/SWPCoreBundle.php, src/SWP/Bundle/CoreBundle/Theme/Asset/AssetsInstaller.php, src/SWP/Bundle/CoreBundle/spec/DependencyInjection/Compiler/OverrideThemeAssetsInstallerPassSpec.php, src/SWP/Bundle/CoreBundle/spec/DependencyInjection/Compiler/OverrideThemeFactoryPassSpec.php, src/SWP/Bundle/CoreBundle/spec/DependencyInjection/Compiler/OverrideThemePathResolverPassSpec.php
| BC breaks?    | yes
| Fixed tickets | [SWP-254](https://dev.sourcefabric.org/browse/SWP-254)
=> [Theme] update theme bundle

.scrutinizer.yml, CHANGELOG.md, PULL_REQUEST_TEMPLATE.md, app/AppKernel.php, app/config/config.yml, docs/templates_system/templates_caching.rst, src/SWP/Bundle/ContentBundle/KeyGenerator/MetaKeyGenerator.php, src/SWP/Bundle/ContentBundle/Model/Article.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml, src/SWP/Bundle/ContentBundle/Tests/KeyGenerator/MetaKeyGeneratorTest.php, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/views/article.html.twig, src/SWP/Component/TemplatesSystem/Gimme/Context/Context.php
=> [WIP] [Templates System] add custom cache key generator for meta objects

CHANGELOG.md, src/SWP/Bundle/ContentBundle/Factory/ArticleFactory.php, src/SWP/Bundle/ContentBundle/spec/Factory/ArticleFactorySpec.php, src/SWP/Component/Bridge/Model/ItemInterface.php
| Fixed tickets             | [SWP-263](https://dev.sourcefabric.org/browse/SWP-263)
=> [ContentBundle][Bridge] Article's body is not pre-filled

src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php, src/SWP/Bundle/ContentBundle/Manager/MediaManager.php, src/SWP/Bundle/ContentBundle/Manager/MediaManagerInterface.php, src/SWP/Bundle/ContentBundle/Tests/Controller/ContentPushControllerTest.php
| Fixed tickets             | [#SWP-273](https://dev.sourcefabric.org/browse/SWP-273)
=> [Content Bundle] improve handling amazon mediaId format

.scrutinizer.yml, app/Resources/meta/article.yml, src/SWP/Bundle/ContentBundle/Enhancer/EnhancerInterface.php, src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleMediaListener.php, src/SWP/Bundle/ContentBundle/Factory/ArticleFactory.php, src/SWP/Bundle/ContentBundle/Form/Type/ArticleType.php, src/SWP/Bundle/ContentBundle/Form/Type/MediaFileType.php, src/SWP/Bundle/ContentBundle/Form/Type/RouteType.php, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Tests/Controller/ContentPushControllerTest.php, src/SWP/Bundle/ContentBundle/Tests/EventListener/ProcessArticleMediaListenerTest.php, src/SWP/Bundle/CoreBundle/Resolver/TemplateNameResolver.php, src/SWP/Bundle/CoreBundle/Resolver/TemplateNameResolverInterface.php, src/SWP/Bundle/CoreBundle/Routing/MetaRouter.php, src/SWP/Bundle/CoreBundle/Theme/Configuration/TenantableConfigurationSourceFactory.php, src/SWP/Bundle/CoreBundle/Theme/Configuration/ThemeConfiguration.php, src/SWP/Bundle/CoreBundle/Theme/Model/Theme.php, src/SWP/Bundle/CoreBundle/Theme/Model/ThemeInterface.php, src/SWP/Bundle/FixturesBundle/DataFixtures/PHPCR/LoadCollectionRouteArticles.php, src/SWP/Bundle/FixturesBundle/DataFixtures/PHPCR/LoadMediaData.php, src/SWP/Bundle/MultiTenancyBundle/Command/CreateTenantCommand.php, src/SWP/Bundle/TemplateEngineBundle/EventSubscriber/HttpCacheSubscriber.php, src/SWP/Component/MultiTenancy/Resolver/TenantResolver.php, src/SWP/Component/TemplatesSystem/Gimme/Meta/Meta.php
=> [Content Bundle] Convert body images to article media

.scrutinizer.yml, CHANGELOG.md, docs/templates_system/templates_features.rst, src/SWP/Bundle/ContentBundle/Doctrine/ODM/PHPCR/File.php, src/SWP/Bundle/ContentBundle/Doctrine/ODM/PHPCR/Image.php, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Loader/ArticleMediaLoader.php, src/SWP/Bundle/ContentBundle/Tests/Controller/ContentPushControllerTest.php, src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php, src/SWP/Bundle/CoreBundle/Routing/MetaRouter.php, src/SWP/Bundle/CoreBundle/Tests/Controller/MetaRouterTest.php, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/article.html.twig, src/SWP/Bundle/TemplateEngineBundle/Resources/views/pagination.html.twig, src/SWP/Component/TemplatesSystem/Gimme/Context/Context.php, src/SWP/Component/TemplatesSystem/Gimme/Loader/ArticleLoader.php, src/SWP/Component/TemplatesSystem/Gimme/Loader/LoaderInterface.php, src/SWP/Component/TemplatesSystem/Gimme/Meta/Meta.php, src/SWP/Component/TemplatesSystem/Gimme/Meta/MetaCollection.php, src/SWP/Component/TemplatesSystem/Gimme/Meta/MetaCollectionInterface.php, src/SWP/Component/TemplatesSystem/Gimme/Meta/MetaInterface.php, src/SWP/Component/TemplatesSystem/Tests/Loader/ArticleLoaderTest.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/GimmeListNodeTest.php, src/SWP/Component/TemplatesSystem/Twig/Node/GimmeListNode.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Context/ContextSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Loader/ArticleLoaderSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Meta/MetaCollectionSpec.php
| Fixed tickets             | [#SWP-267](https://dev.sourcefabric.org/browse/SWP-267)
introduce MetaCollection class, add totalLength parameter to gimmelist loop variables, use MetaCollection in existing loaders, add default pagination template and document it
=> [Template Component][TemplateEngine Bundle] [feature] lists pagination

app/phpunit.xml.dist, src/SWP/Bundle/ContentBundle/Loader/ArticleMediaLoader.php, src/SWP/Bundle/ContentBundle/Tests/Controller/ContentPushControllerTest.php, src/SWP/Bundle/ContentBundle/Tests/EventListener/HttpCacheHeaderListenerTest.php, src/SWP/Component/TemplatesSystem/Tests/Gimme/Widget/HtmlWidgetTest.php, src/SWP/Component/TemplatesSystem/Tests/Loader/ArticleLoaderTest.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/ContainerNodeTest.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/GimmeListNodeTest.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/GimmeNodeTest.php
=> improve tests, add better data checking in ArticleMediaLoader

composer.json, composer.lock
=> [maintenance] update dependecies

CHANGELOG.md, src/SWP/Bundle/BridgeBundle/Resources/config/services.yml, src/SWP/Bundle/BridgeBundle/Serializer/PackageSubscriber.php, src/SWP/Bundle/BridgeBundle/spec/Serializer/PackageSubscriberSpec.php, src/SWP/Component/Bridge/Model/Item.php, src/SWP/Component/Bridge/Model/ItemInterface.php, src/SWP/Component/Bridge/Model/Package.php, src/SWP/Component/Bridge/Model/PackageInterface.php, src/SWP/Component/Bridge/Transformer/JsonToPackageTransformer.php
| Fixed tickets             | [SWP-289](https://dev.sourcefabric.org/browse/SWP-289)
=> [BridgeBundle] Invalid argument supplied for foreach() - content push

.scrutinizer.yml, app/phpunit.xml.dist, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml, src/SWP/Bundle/ContentBundle/Tests/Loader/ArticleLoaderTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/collection.html.twig
| Fixed tickets             | comma separated list of tickets fixed by the PR
=> [bug] use context route in article loader when route not defined in parameters

app/phpunit.xml.dist
=> scan all directories (not only tests) in coverage check

composer.lock
=> update vendors versions

src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleMediaListener.php
=> articlemedia handling fix (package with text, image items)

src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Item.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Package.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.Article.yml, src/SWP/Component/Bridge/Model/BaseContent.php, src/SWP/Component/Bridge/Model/ContentInterface.php, src/SWP/Component/Bridge/spec/Model/BaseContentSpec.php
=> expose metadata in API and store services in package

app/AppCache.php, app/config/config.yml, web/app.php
=> [config] controll better HttpCache sybscribers, add namespace to cache keys, disable symfony proxy in production

docs/bundles/SWPContentBundle/usage.rst, src/SWP/Bundle/ContentBundle/Resources/config/services.yml, src/SWP/Bundle/ContentBundle/Rule/Applicator/ArticleRuleApplicator.php, src/SWP/Bundle/ContentBundle/Tests/Controller/ArticleAutoPublishTest.php, src/SWP/Bundle/ContentBundle/Tests/Controller/ArticleTitleChangeTest.php, src/SWP/Bundle/ContentBundle/spec/Rule/Applicator/ArticleRuleApplicatorSpec.php, src/SWP/Bundle/CoreBundle/Tests/Controller/RuleControllerTest.php, src/SWP/Bundle/RuleBundle/composer.json, src/SWP/Bundle/StorageBundle/composer.json
| Tests pass?               | yes|no
| Fixed tickets             | [SWP-305](https://dev.sourcefabric.org/browse/SWP-305)
TODO:
=> Allow to manage article autopublishing feature by rules

CHANGELOG.md, README.md, app/SymfonyRequirements.php, app/config/config.yml, app/config/parameters.yml.dist, app/config/routing.yml, app/config/session.yml, src/SWP/Bundle/CoreBundle/Controller/DefaultController.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Security/Storage/DynamicDomainSessionStorage.php, src/SWP/Bundle/CoreBundle/Tests/Security/Storage/DynamicDomainSessionStorageTest.php, src/SWP/Bundle/CoreBundle/Tests/ServicesTest.php
=> [maintenance] add project requirements, implement memcached session handler

src/SWP/Bundle/MultiTenancyBundle/composer.json
=> [MultitenancyBundle] fix test vendor versions

app/config/config.yml, app/config/config_test.yml, src/SWP/Bundle/ContentBundle/Doctrine/ODM/PHPCR/ArticleRepository.php, src/SWP/Bundle/ContentBundle/Factory/KnpPaginatorRepresentationFactory.php, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Pagination/PaginationInterface.php, src/SWP/Bundle/CoreBundle/Controller/RuleController.php, src/SWP/Bundle/CoreBundle/Controller/TenantController.php, src/SWP/Bundle/TemplateEngineBundle/Controller/ContainerController.php, src/SWP/Bundle/TemplateEngineBundle/Controller/MenuController.php, src/SWP/Bundle/TemplateEngineBundle/Controller/MenuNodeController.php, src/SWP/Bundle/TemplateEngineBundle/Controller/WidgetController.php, src/SWP/Bundle/TemplateEngineBundle/Tests/Controller/WidgetControllerTest.php
| Deprecations?             |no
| Fixed tickets             | [SWP-319](https://dev.sourcefabric.org/browse/SWP-319)
=> add missing pagination parameters to lists, improve article load query

app/config/config.yml, docs/bundles/SWPRuleBundle/usage.rst, src/SWP/Bundle/RuleBundle/Resources/config/services.yml, src/SWP/Component/Rule/Evaluator/RuleEvaluator.php, src/SWP/Component/Rule/spec/Evaluator/RuleEvaluatorSpec.php
| Fixed tickets             | [SWP-295](https://dev.sourcefabric.org/browse/SWP-295)
=> SWP-295 - Create a separate logger channel for rules

src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml, src/SWP/Bundle/ContentBundle/Tests/Controller/ContentPushControllerTest.php, src/SWP/Bundle/ContentBundle/Tests/EventListener/ProcessArticleMediaListenerTest.php, src/SWP/Bundle/ContentBundle/Transformer/PackageToArticleTransformer.php, src/SWP/Bundle/ContentBundle/spec/Transformer/PackageToArticleTransformerSpec.php
| Fixed tickets             | [SWP-298](https://dev.sourcefabric.org/browse/SWP-298)
=> [Content Bundle] fix pushing this same content with media multiple times (corrections)

docs/cookbook/templates/complex_static_pages_widgets.rst
| Bug fix?                  |no
Docs entry written
=> Cookbook example: building complex static pages with widgets

src/SWP/Bundle/ContentBundle/Controller/ArticleController.php, src/SWP/Bundle/ContentBundle/Controller/RouteController.php, src/SWP/Bundle/ContentBundle/Doctrine/ODM/PHPCR/Article.php, src/SWP/Bundle/ContentBundle/Doctrine/ODM/PHPCR/ArticleRepository.php, src/SWP/Bundle/ContentBundle/Factory/KnpPaginatorRepresentationFactory.php, src/SWP/Bundle/ContentBundle/Provider/ArticleProvider.php, src/SWP/Bundle/ContentBundle/Resources/config/providers.yml, src/SWP/Bundle/ContentBundle/Resources/config/serializer/CmfRoutingBundle/Model.Route.yml, src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.Article.yml, src/SWP/Bundle/ContentBundle/Service/RouteService.php, src/SWP/Bundle/ContentBundle/Tests/ContentRepositoryTest.php, src/SWP/Bundle/ContentBundle/Tests/Controller/ArticleControllerTest.php, src/SWP/Bundle/ContentBundle/Tests/Factory/KnpPaginatorRepresentationFactoryTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentControllerTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/PHPCR/LoadArticlesData.php, src/SWP/Bundle/MultiTenancyBundle/Initializer/PHPCRBasePathsInitializer.php, src/SWP/Bundle/TemplateEngineBundle/Controller/MenuController.php, web/app_test.php
| Fixed tickets             | [SWP-285](https://dev.sourcefabric.org/browse/SWP-285), [SWP-284](https://dev.sourcefabric.org/browse/SWP-284)
=> Api improvements

app/AppKernel.php, app/config/config.yml, app/config/parameters.yml.dist, composer.json, composer.lock, src/SWP/Bundle/MenuBundle/Model/MenuItem.php
| New feature?              | yes|
| Changelog update required | yes|no
| Fixed tickets             | [SWP-368](https://dev.sourcefabric.org/browse/SWP-368)
=> Add CORS headers support

src/SWP/Bundle/CoreBundle/composer.json
| Bug fix?                  |no
| New feature?              |no
=> [CoreBundle] add basic composer.json file

app/config/routing.yml, src/SWP/Bundle/CoreBundle/Controller/ContainerController.php, src/SWP/Bundle/CoreBundle/Controller/DefaultController.php, src/SWP/Bundle/CoreBundle/Controller/MenuController.php, src/SWP/Bundle/CoreBundle/Controller/RuleController.php, src/SWP/Bundle/CoreBundle/Controller/TenantController.php, src/SWP/Bundle/CoreBundle/Controller/UserController.php, src/SWP/Bundle/CoreBundle/Controller/WidgetController.php, src/SWP/Bundle/CoreBundle/EventListener/ResourceResponseListener.php, src/SWP/Bundle/CoreBundle/Form/Type/ThemeNameChoiceType.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Response/ResourcesListResponse.php, src/SWP/Bundle/CoreBundle/Response/ResourcesListResponseInterface.php, src/SWP/Bundle/CoreBundle/Response/ResponseContext.php, src/SWP/Bundle/CoreBundle/Response/ResponseContextInterface.php, src/SWP/Bundle/CoreBundle/Response/SingleResourceResponse.php, src/SWP/Bundle/CoreBundle/Response/SingleResourceResponseInterface.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContainerControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/WidgetControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/EventListener/ResourceResponseListenerTest.php, src/SWP/Bundle/CoreBundle/Tests/Response/ResourcesListResponseTest.php, src/SWP/Bundle/CoreBundle/Tests/Response/ResponseContextTest.php, src/SWP/Bundle/CoreBundle/Tests/Response/SingleResourceResponseTest.php, src/SWP/Bundle/CoreBundle/Tests/Version/VersionTest.php
=> Move Templates Engine controllers to core, add and use custom response class for api controllers

CHANGELOG.md, app/config/routing.yml, app/config/security.yml, docs/cookbooks/templates/complex_static_pages_widgets.rst, docs/cookbooks/templates/index.rst, docs/cookbooks/templates/users_registration_and_login.rst, src/SWP/Bundle/BridgeBundle/.travis.yml, src/SWP/Bundle/ContentBundle/Model/RouteTrait.php, src/SWP/Bundle/CoreBundle/Controller/DefaultController.php, src/SWP/Bundle/CoreBundle/Controller/UserController.php, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/index.html.twig
| Fixed tickets             | [SWP-232](https://dev.sourcefabric.org/browse/SWP-232)
* add documentation cookbook
* set current page meta in homepage
=> [Core Bundle] configure user authentication 

docs/bundles/SWPStorageBundle/register_storage.rst, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Organization.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Tenant.orm.yml, src/SWP/Bundle/MultiTenancyBundle/DependencyInjection/Configuration.php, src/SWP/Bundle/MultiTenancyBundle/Resources/config/doctrine-orm/Organization.orm.yml, src/SWP/Bundle/MultiTenancyBundle/Resources/config/doctrine-orm/Tenant.orm.yml, src/SWP/Bundle/StorageBundle/DependencyInjection/Compiler/DoctrineTargetEntitiesResolverPass.php, src/SWP/Bundle/StorageBundle/DependencyInjection/Extension/Extension.php, src/SWP/Bundle/StorageBundle/DependencyInjection/SWPStorageExtension.php, src/SWP/Bundle/StorageBundle/EventListener/AbstractDoctrineSubscriber.php, src/SWP/Bundle/StorageBundle/EventListener/ORMMappedSuperclassSubscriber.php, src/SWP/Bundle/StorageBundle/Resources/config/listeners.yml, src/SWP/Bundle/StorageBundle/SWPStorageBundle.php
| Fixed tickets             | [SWP-420](https://dev.sourcefabric.org/browse/SWP-420)
=> Entities inheritence

app/config/config.yml, src/SWP/Bundle/ContentBundle/spec/Doctrine/ORM/ContentListSpec.php, src/SWP/Bundle/CoreBundle/Controller/MenuController.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/MenuItem.orm.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/MenuControllerTest.php, src/SWP/Bundle/MenuBundle/DependencyInjection/Configuration.php, src/SWP/Bundle/MenuBundle/Form/Type/MenuType.php, src/SWP/Bundle/MenuBundle/Model/MenuItem.php, src/SWP/Bundle/MenuBundle/Resources/config/doctrine-orm/MenuItem.orm.yml, src/SWP/Bundle/MenuBundle/Resources/config/serializer/Model.MenuItem.yml
| Fixed tickets             | [SWP-397](https://dev.sourcefabric.org/browse/SWP-397), [SWP-398](https://dev.sourcefabric.org/browse/SWP-398)
This PR includes:
- missing ContentList spec
- Documentation for PATCH menu API endpoint doesn't show fields
- Allow same value for menu name and menu label
- introduce new inheritance mapping for menu bundle and small fixes
=> [MenuBundle] fixes

src/SWP/Bundle/CoreBundle/Security/Authenticator/TokenAuthenticator.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadContainerWidgetsData.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadContainersData.php
=> remove 'Basic' from from token & fixtures fix

.gitignore, .rmt.yml, bin/UpdateApplicationVersion.php, composer.json, composer.lock, src/SWP/Bundle/CoreBundle/Version/Version.php
=> [maintenance] Add RMT confguration and version updater

src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/translations/messages.de.xlf, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/translations/messages.en.xlf
=> update demo theme translations

docs/bundles/SWPMultiTenancyBundle/prerequisites.rst, src/SWP/Bundle/MultiTenancyBundle/.travis.yml, src/SWP/Bundle/MultiTenancyBundle/composer.json, src/SWP/Component/MultiTenancy/.travis.yml, src/SWP/Component/MultiTenancy/composer.json
| Bug fix?                  |no
=> [Multitenancy] drop php 5 for multitenancy bundle and component

src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php, src/SWP/Bundle/ContentBundle/Controller/MediaController.php, src/SWP/Component/Bridge/Validator/NinjsValidator.php
| Bug fix?                  | yes|
=> Content push fixes

src/SWP/Bundle/MenuBundle/Doctrine/ORM/MenuItemRepository.php
| Fixed tickets             | SWP-506
**Before** (frontpage with default theme):
**After** (frontpage with default theme):
Not sure yet how it will behave when there are more levels.
=> Optimize menu query

src/SWP/Component/TemplatesSystem/Gimme/Context/Context.php
| Fixed tickets             | [SWP-560](https://dev.sourcefabric.org/browse/SWP-560)
=> [Templates System] Don't overrite context variables with meta registration

CHANGELOG.md, docs/components/TemplatesSystem/features/customTags/gimmelist.rst, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Provider/AbstractProvider.php, src/SWP/Bundle/ContentBundle/Provider/ORM/ArticleMediaProvider.php, src/SWP/Bundle/ContentBundle/Provider/ORM/ArticleProvider.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Loader/ArticleLoaderTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/app/Resources/fixtures/LoadArticlesData.php
| Fixed tickets             | SWP-523
TODO:
=> Filter articles by metadata in gimmelist

src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Article.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Route.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Article.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Route.orm.yml, src/SWP/Bundle/TemplatesSystemBundle/Resources/config/doctrine-orm/ContainerWidget.orm.yml
Thanks to this we can add the same content (articlea and routes) to every tenant.
=> change unique constraint for routes & articles

src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php, src/SWP/Bundle/ContentBundle/Controller/MediaController.php, src/SWP/Bundle/ContentBundle/DependencyInjection/Compiler/RegisterMediaFactoryPass.php, src/SWP/Bundle/ContentBundle/DependencyInjection/Configuration.php, src/SWP/Bundle/ContentBundle/Doctrine/ArticleMediaRepositoryInterface.php, src/SWP/Bundle/ContentBundle/Doctrine/ImageRepositoryInterface.php, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleMediaRepository.php, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ImageRepository.php, src/SWP/Bundle/ContentBundle/Factory/ORM/MediaFactory.php, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Article.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleMedia.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/File.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Image.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ImageRendition.orm.yml, src/SWP/Bundle/CoreBundle/Model/Image.php, src/SWP/Bundle/CoreBundle/Model/ImageInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Image.orm.yml, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
| Fixed tickets             | SWP-568
=> [ContentBundle] article media handling - multitenancy

src/SWP/Bundle/ContentListBundle/Form/Type/ContentListType.php, src/SWP/Bundle/ContentListBundle/Resources/config/validation.yml, src/SWP/Bundle/ContentListBundle/Validator/Constraints/ContainsValidDate.php, src/SWP/Bundle/ContentListBundle/Validator/Constraints/ContainsValidDateValidator.php, src/SWP/Bundle/ContentListBundle/spec/Validator/Constraints/ContainsValidDateSpec.php, src/SWP/Bundle/ContentListBundle/spec/Validator/Constraints/ContainsValidDateValidatorSpec.php, src/SWP/Bundle/CoreBundle/Controller/ContentListController.php, src/SWP/Bundle/CoreBundle/EventListener/RemoveItemsListener.php
| Fixed tickets             | SWP-579
=> Content list criteria validation

app/config/config.yml, app/config/parameters.yml.dist
| Fixed tickets             | [SWP-556](https://dev.sourcefabric.org/browse/SWP-556)
=> [Maintenance] add option to configure trusted proxies from parametersyml

composer.json, composer.lock
=> [Maintenance] raise twig version, update other dependencies

src/SWP/Bundle/CoreBundle/Controller/MenuController.php, src/SWP/Bundle/MenuBundle/Manager/MenuItemManager.php, src/SWP/Bundle/MenuBundle/Manager/MenuItemManagerInterface.php, src/SWP/Bundle/MenuBundle/Resources/config/services.yml, src/SWP/Bundle/MenuBundle/spec/Manager/MenuItemManagerSpec.php
| Fixed tickets             | [SWP-582](https://dev.sourcefabric.org/browse/SWP-582)
=> [MenuBundle] update menu extras on update

app/config/config.yml, src/SWP/Bundle/TemplatesSystemBundle/DependencyInjection/Configuration.php, src/SWP/Bundle/TemplatesSystemBundle/Repository/ContainerRepository.php, src/SWP/Bundle/TemplatesSystemBundle/Repository/ContainerWidgetRepository.php, src/SWP/Bundle/TemplatesSystemBundle/Service/ContainerService.php, src/SWP/Component/TemplatesSystem/Repository/ContainerWidgetRepositoryInterface.php
| Tests pass?               | yes|no
| Fixed tickets             | SWP-569
=> Fixed container service to be tenant aware

src/SWP/Bundle/CoreBundle/Model/WidgetModel.php, src/SWP/Bundle/CoreBundle/Model/WidgetModelInterface.php, src/SWP/Bundle/CoreBundle/spec/EventListener/MenuWidgetCreateListenerSpec.php, src/SWP/Bundle/CoreBundle/spec/EventListener/MenuWidgetDeleteListenerSpec.php, src/SWP/Bundle/TemplatesSystemBundle/Model/WidgetModel.php, src/SWP/Bundle/TemplatesSystemBundle/Widget/TemplatingWidgetHandler.php, src/SWP/Component/TemplatesSystem/Gimme/Model/WidgetModelInterface.php
=> [Maintenance] remove not needed dependency

app/config/config.yml, composer.json, composer.lock, src/SWP/Bundle/CoreBundle/Twig/TwigCacheProfilerExtension.php
=> [Maintenance] fix Twig Cache extension registration

src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php, src/SWP/Bundle/ContentBundle/Controller/MediaController.php, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ImageRepository.php, src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleMediaListener.php, src/SWP/Bundle/ContentBundle/Factory/ORM/MediaFactory.php, src/SWP/Bundle/ContentBundle/Manager/MediaManager.php, src/SWP/Bundle/ContentBundle/Model/ArticleMedia.php, src/SWP/Bundle/ContentBundle/Model/ArticleMediaInterface.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/ArticleTitleChangeTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/ContentPushControllerTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/EventListener/ProcessArticleMediaListenerTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/app/Resources/fixtures/LoadArticlesMediaData.php
| Fixed tickets             | [SWP-585](https://dev.sourcefabric.org/browse/SWP-585)
=> [Content Bundle] support new amazon mediaId format

src/SWP/Bundle/CoreBundle/DependencyInjection/SWPCoreExtension.php, src/SWP/Bundle/MenuBundle/Manager/MenuItemManager.php, src/SWP/Bundle/StorageBundle/DependencyInjection/Extension/Extension.php
| Bug fix?                  |no
| Fixed tickets             | [SWP-586](https://dev.sourcefabric.org/browse/SWP-586)
=> [Core Bundle][Storage] Add allways used classes to compiled file

CHANGELOG.md, src/SWP/Bundle/CoreBundle/Controller/ContainerController.php, src/SWP/Bundle/CoreBundle/Resources/views/Container/render.html.twig, src/SWP/Bundle/CoreBundle/Tests/Controller/ContainerControllerTest.php, src/SWP/Bundle/TemplatesSystemBundle/Model/Container.php, src/SWP/Component/TemplatesSystem/Gimme/Model/ContainerInterface.php
| Fixed tickets             | [SWP-572](https://dev.sourcefabric.org/browse/SWP-572)
=> [Core Bundle] Add api for rendering single container (and it content)

src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
| Fixed tickets             | SWP-595
=> [FixturesBundle] added two more renditions to fixtures

src/SWP/Bundle/CoreBundle/DependencyInjection/Configuration.php, src/SWP/Bundle/CoreBundle/Model/ApiKey.php, src/SWP/Bundle/CoreBundle/Model/ApiKeyInterface.php, src/SWP/Bundle/CoreBundle/Model/User.php, src/SWP/Bundle/CoreBundle/Model/UserInterface.php, src/SWP/Bundle/CoreBundle/Repository/ApiKeyRepository.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/ApiKey.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/User.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Security/Authenticator/TokenAuthenticator.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentControllerTest.php, src/SWP/Bundle/CoreBundle/spec/Model/ApiKeySpec.php, src/SWP/Bundle/CoreBundle/spec/Model/UserSpec.php
| Fixed tickets             | SWP-575
- when you request API using token that belongs to user from the same organization, you will be able to fetch it's data (we can later introduce some kind of setting per api key if it should be shared with the organization or we implement api keys per organization)
- if you want to request API of `tenant1` with api key which doesn't belong to tenant1's ogranization, access will not be granted
=> handle authentication for multitenancy

docker/php7-fpm/Dockerfile
Fix "zip extension and unzip command are both missing" errors.
| Fixed tickets             | comma separated list of tickets fixed by the PR
=> Fix composer's zip errors

src/SWP/Bundle/CoreBundle/Tests/Controller/ContainerControllerTest.php, src/SWP/Bundle/TemplatesSystemBundle/Container/SimpleContainer.php, src/SWP/Bundle/TemplatesSystemBundle/Tests/Container/SimpleContainerTest.php, src/SWP/Component/TemplatesSystem/Gimme/Widget/AbstractWidgetHandler.php, src/SWP/Component/TemplatesSystem/Gimme/Widget/WidgetHandlerInterface.php
| Fixed tickets             | [SWP-588](https://dev.sourcefabric.org/browse/SWP-588)
=> Swp 588 render custom class with widgets

src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php
| Fixed tickets             | no
=> [ContentBundle] check image not media on asset fetch action

src/SWP/Bundle/CoreBundle/Resources/config/twig.yml, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/menu_template.html.twig, src/SWP/Bundle/CoreBundle/Tests/TemplateMenuTest.php, src/SWP/Bundle/CoreBundle/Twig/MenuExtension.php, src/SWP/Bundle/CoreBundle/Twig/RoutingExtension.php, src/SWP/Bundle/MenuBundle/Provider/OrmMenuProvider.php
| Fixed tickets             | SWP-557
- this PR fixes also issues with rendering profiler
=> Silent exception when non-existing menu is used in theme

app/AppKernel.php, composer.json, composer.lock, docs/templates_system/article_media.rst, src/SWP/Bundle/TemplatesSystemBundle/Repository/ContainerRepository.php
=> Add Doctrine profiler, left join container data

app/config/config.yml, composer.lock
List of updated dependencies:
```
- Updating symfony/symfony (v3.1.9 => v3.1.10) Loading from cache
- Updating sensio/framework-extra-bundle (v3.0.19 => v3.0.22) Downloading: 100%
- Updating doctrine/dbal (v2.5.10 => v2.5.12) Downloading: 100%
- Updating friendsofsymfony/user-bundle (v2.0.0-beta1 => 2.0.0-beta2) Loading from cache
- Updating league/flysystem (1.0.33 => 1.0.35) Downloading: 100%
- Updating oneup/flysystem-bundle (1.7.0 => 1.10.0) Loading from …
```
=> [Maintenance] update project dependencies

app/migrations/Version20170217123721.php
=> [Revisions] Rename migration file

src/SWP/Bundle/MultiTenancyBundle/Command/CreateOrganizationCommand.php, src/SWP/Bundle/MultiTenancyBundle/Tests/Command/CreateOrganizationCommandTest.php, src/SWP/Bundle/MultiTenancyBundle/Tests/DependencyInjection/Compiler/TenantAwareRouterCompilerPassTest.php, src/SWP/Bundle/MultiTenancyBundle/composer.json
| New feature?              | improvement 
| Fixed tickets             | SWP-622
=> [MultitenancyBundle] add code to new organization command output

src/SWP/Bundle/MultiTenancyBundle/Tests/DependencyInjection/Compiler/TenantAwareRouterCompilerPassTest.php
=> [MultitenancyBundle] fix test

app/config/parameters.yml.dist, src/SWP/Bundle/CoreBundle/Controller/AuthController.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContainerControllerTest.php, src/SWP/Bundle/TemplatesSystemBundle/Service/ContainerService.php
| Fixed tickets             | SWP-650
=> base url for Superdesk servers & SWP-650

CHANGELOG.md, src/SWP/Bundle/MultiTenancyBundle/Command/ListTenantsCommand.php, src/SWP/Bundle/MultiTenancyBundle/Tests/Command/ListTetantsCommandTest.php
| Fixed tickets             | SWP-623
=> [MultitenancyBundle] add command to list tenants

app/migrations/Version20170221091231.php, src/SWP/Bundle/CoreBundle/EventSubscriber/HttpCacheSubscriber.php, src/SWP/Bundle/CoreBundle/Service/RevisionAwareContainerService.php, src/SWP/Bundle/TemplatesSystemBundle/Service/ContainerServiceInterface.php
=> [Revisions] add migration for missing revisions

app/migrations/Version20170221140709.php
=> [Revisions] add revisions to existing containers

app/migrations/Version20170222142920.php
=> fixed migration script

docs/components/TemplatesSystem/features/twig_nodes.rst, src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/CoreBundle/Controller/AuthController.php, src/SWP/Bundle/CoreBundle/Controller/StaticThemeAssetsController.php, src/SWP/Bundle/CoreBundle/Repository/ApiKeyRepository.php, src/SWP/Bundle/CoreBundle/Repository/ApiKeyRepositoryInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/AuthControllerTest.php, src/SWP/Bundle/CoreBundle/Theme/AmpThemeLoader.php, src/SWP/Bundle/CoreBundle/spec/Theme/AmpThemeLoaderSpec.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadContainersData.php, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/views/article.html.twig, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/views/base.html.twig, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/views/page.html.twig
| Fixed tickets             | SWP-687
=> [BUG]  Handle duplicated tokens and users

src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php
=> fixed join for media

CHANGELOG.md, src/SWP/Bundle/ContentBundle/Controller/ArticleController.php, src/SWP/Bundle/ContentBundle/Model/ArticleInterface.php, src/SWP/Bundle/ContentBundle/Tests/Functional/ContentRepositoryTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/ArticleControllerTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/app/Resources/fixtures/LoadArticlesData.php, src/SWP/Bundle/ContentBundle/spec/Model/ArticleSpec.php
| Fixed tickets             | SWP-688
=> Allow to filter articles by status in API

src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/RevisionControllerTest.php
add more tests for revision publishing, fix model used for revision log
| Fixed tickets             | SWP-702
=> [Fix] fix adding revision log after publishing revision

src/SWP/Bundle/MultiTenancyBundle/Command/CreateTenantCommand.php, src/SWP/Bundle/MultiTenancyBundle/Tests/Command/CreateTenantCommandTest.php, src/SWP/Bundle/MultiTenancyBundle/composer.json
=> imvprove create tenant command

app/config/config.yml, app/migrations/Version20170302121124.php, src/SWP/Bundle/CoreBundle/Controller/OrganizationController.php, src/SWP/Bundle/CoreBundle/EventSubscriber/ArticlePublishSubscriber.php, src/SWP/Bundle/CoreBundle/EventSubscriber/ArticleTenantSubscriber.php, src/SWP/Bundle/CoreBundle/Model/Article.php, src/SWP/Bundle/CoreBundle/Model/ArticleInterface.php, src/SWP/Bundle/CoreBundle/Model/FacebookInstantArticlesArticle.php, src/SWP/Bundle/CoreBundle/Model/FacebookInstantArticlesArticleInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Article.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/OrganizationControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/OrganizationArticlesTest.php, src/SWP/Bundle/CoreBundle/spec/EventSubscriber/ArticlePublishSubscriberSpec.php, src/SWP/Bundle/CoreBundle/spec/EventSubscriber/ArticleTenantSubscriberSpec.php, src/SWP/Bundle/CoreBundle/spec/Model/ArticleSpec.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadAmpHtmlData.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadCollectionRouteArticles.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php, src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/test/organization_articles.yml, src/SWP/Bundle/FixturesBundle/WebTestCase.php, src/SWP/Bundle/MultiTenancyBundle/EventListener/OrganizationSubscriber.php, src/SWP/Bundle/MultiTenancyBundle/EventListener/TenantSubscriber.php, src/SWP/Bundle/MultiTenancyBundle/Resources/config/listeners.yml, src/SWP/Bundle/MultiTenancyBundle/spec/EventListener/OrganizationSubscriberSpec.php, src/SWP/Component/MultiTenancy/Model/OrganizationAwareInterface.php, src/SWP/Component/MultiTenancy/Model/OrganizationAwareTrait.php
| Fixed tickets             | SWP-690
TODO:
=> SWP-690 - Add option to create article without tenant but only with organization

src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/ContentListBundle/composer.json, src/SWP/Bundle/FacebookInstantArticlesBundle/composer.json, src/SWP/Bundle/FixturesBundle/composer.json, src/SWP/Bundle/MenuBundle/composer.json, src/SWP/Bundle/MultiTenancyBundle/composer.json, src/SWP/Bundle/MultiTenancyBundle/spec/EventListener/OrganizationSubscriberSpec.php, src/SWP/Bundle/RuleBundle/composer.json, src/SWP/Bundle/StorageBundle/composer.json, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Component/Bridge/composer.json, src/SWP/Component/Common/composer.json, src/SWP/Component/ContentList/composer.json, src/SWP/Component/MultiTenancy/composer.json, src/SWP/Component/Revision/composer.json, src/SWP/Component/Rule/composer.json, src/SWP/Component/Storage/composer.json, src/SWP/Component/TemplatesSystem/composer.json
| Deprecations?             |no
=> adjust packages and bundles versions

src/SWP/Bridge/JMSSerializerBundle/Tests/JMSSerializerTest.php, src/SWP/Bridge/JMSSerializerBundle/phpunit.xml.dist, src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/ContentListBundle/composer.json, src/SWP/Bundle/MenuBundle/.travis.yml, src/SWP/Bundle/MultiTenancyBundle/composer.json
=> Add missing test, work on dependencies

src/SWP/Bundle/CoreBundle/Controller/ContainerController.php, src/SWP/Bundle/CoreBundle/Controller/ContentPushController.php, src/SWP/Bundle/CoreBundle/Controller/RevisionController.php
| Fixed tickets             | SWP-718
=> SWP-718 - added trailing slash to certain API endpoints

src/SWP/Bundle/CoreBundle/Tests/Controller/WidgetControllerTest.php, src/SWP/Bundle/TemplatesSystemBundle/Form/Type/WidgetType.php
| Fixed tickets             | SWP-652
=> SWP-652 - standardize boolean form values

docs/components/TemplatesSystem/features/customTags/gimmelist.rst, src/SWP/Bundle/CoreBundle/Controller/WidgetController.php, src/SWP/Bundle/CoreBundle/Tests/Controller/WidgetControllerTest.php, src/SWP/Bundle/TemplatesSystemBundle/Model/WidgetModel.php
| Fixed tickets             | SWP-651
=> Allow to specify widget type by his class instead id

app/migrations/Version20170317110311.php, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/articles_by_metadata_v1.html.twig, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/articles_by_metadata_v2.html.twig, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/articles_by_metadata_v3.html.twig, src/SWP/Bundle/CoreBundle/Tests/TwigRenderArticlesByCriteriaTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesWithMetadata.php, src/SWP/Bundle/FixturesBundle/Registry/FixtureRegistry.php
| Fixed tickets             | SWP-721
=> SWP-721 - Gimmelist filtering by metadata throws error

src/SWP/Bundle/TemplatesSystemBundle/Tests/Functional/Widget/MenuWidgetTest.php, src/SWP/Bundle/TemplatesSystemBundle/Widget/TemplatingWidgetHandler.php
| Fixed tickets             | SWP-662
=> SWP- 662 - non existing widget template breaks the page

src/SWP/Bundle/MultiTenancyBundle/Resources/config/doctrine-orm/Tenant.orm.yml
| Fixed tickets             | SWP-719
=> SWP- 719 - The whole organization is removed if one of the tenants is removed

src/SWP/Bundle/CoreBundle/Provider/ContainerProvider.php
| Fixed tickets             | SWP-722
=> [Revisions] check working and published revision for containers

src/SWP/Bundle/CoreBundle/Model/WidgetModel.php, src/SWP/Bundle/TemplatesSystemBundle/Model/WidgetModel.php, src/SWP/Component/TemplatesSystem/Gimme/Model/WidgetModelInterface.php, src/SWP/Component/TemplatesSystem/Tests/Gimme/Model/WidgetModel.php
| Fixed tickets             | SWP-664
=> Fix setting type by id

src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Loader/ArticleLoaderTest.php
| Fixed tickets             | SWP-724
=> use this same criteria for count query as for fetch

CHANGELOG.md, src/SWP/Bundle/BridgeBundle/EventListener/ValidationExceptionListener.php, src/SWP/Bundle/BridgeBundle/EventListener/ValidationListener.php, src/SWP/Bundle/BridgeBundle/Exception/ValidationException.php, src/SWP/Bundle/BridgeBundle/Resources/config/services.yml, src/SWP/Bundle/BridgeBundle/Resources/config/validation.yml, src/SWP/Bundle/BridgeBundle/Tests/Functional/app/config/default.yml, src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/ContentPushControllerTest.php, src/SWP/Component/Bridge/Events.php
| Fixed tickets             | SWP-667
=> SWP-667 - Add slug limit for article

src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideThemeLoaderPass.php, src/SWP/Bundle/CoreBundle/SWPCoreBundle.php, src/SWP/Bundle/CoreBundle/Theme/Loader/TenantAwareThemeLoader.php, src/SWP/Bundle/CoreBundle/Version/Version.php, src/SWP/Bundle/TemplatesSystemBundle/Factory/ContainerWidgetFactory.php
| Fixed tickets             | SWP-693
=> [CoreBundle] load parent theme allways from current tenant

src/SWP/Bundle/ContentBundle/Controller/ArticleController.php, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php, src/SWP/Bundle/ContentBundle/Tests/Functional/ContentRepositoryTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/ArticleControllerTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/app/Resources/fixtures/LoadArticlesData.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
| Fixed tickets             | SWP-660
=> Add more options to filter articles in API

app/migrations/Version20170221091231.php, docs/cookbooks/editors/configure_facebook_instant_articles.rst, src/SWP/Bundle/ContentBundle/ArticleEvents.php, src/SWP/Bundle/ContentBundle/Service/ArticleService.php, src/SWP/Bundle/CoreBundle/EventListener/FacebookInstantArticlesListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Service/FacebookInstantArticlesService.php, src/SWP/Bundle/CoreBundle/Service/FacebookInstantArticlesServiceInterface.php, src/SWP/Bundle/CoreBundle/Tests/Service/FacebookInstantArticlesServiceTest.php, src/SWP/Bundle/FacebookInstantArticlesBundle/Controller/ParsingPreviewController.php
| Fixed tickets             | SWP-436
=> Remove article from Facebook Instant Articles when it's unpublished

src/SWP/Bundle/ContentBundle/EventListener/MimeTypeListener.php, src/SWP/Bundle/ContentListBundle/Form/Type/ContentListItemPositionType.php, src/SWP/Bundle/ContentListBundle/Form/Type/ContentListItemsType.php, src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php, src/SWP/Bundle/CoreBundle/Routing/MetaRouter.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListItemControllerTest.php
| Fixed tickets             | [SWP-742](https://dev.sourcefabric.org/browse/SWP-742)
=> [ContentList] add option to update many content items in content list at once

docs/cookbooks/index.rst, docs/index.rst, docs/manual/introduction.rst
=> Fixes for Vincer's texts; cookbooks illustration

src/SWP/Bundle/BridgeBundle/DependencyInjection/Configuration.php, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Event.Category.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Event.Date.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Event.Location.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Event.OccurStatus.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Event.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Event.Category.yml, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Event.Date.yml, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Event.Location.yml, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Event.OccurStatus.yml, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Event.yml, src/SWP/Bundle/ContentBundle/EventListener/MimeTypeListener.php, src/SWP/Bundle/ContentBundle/Tests/EventListener/MimeTypeListenerTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentControllerTest.php, src/SWP/Bundle/SettingsBundle/Controller/SettingsController.php, src/SWP/Bundle/SettingsBundle/composer.json, src/SWP/Bundle/StorageBundle/DependencyInjection/Compiler/DoctrineTargetEntitiesResolverPass.php, src/SWP/Bundle/StorageBundle/composer.json, src/SWP/Component/Bridge/.travis.yml, src/SWP/Component/Bridge/AUTHORS.md, src/SWP/Component/Bridge/Model/Event.php, src/SWP/Component/Bridge/Model/Event/Category.php, src/SWP/Component/Bridge/Model/Event/CategoryInterface.php, src/SWP/Component/Bridge/Model/Event/Date.php, src/SWP/Component/Bridge/Model/Event/DateInterface.php, src/SWP/Component/Bridge/Model/Event/Location.php, src/SWP/Component/Bridge/Model/Event/LocationInterface.php, src/SWP/Component/Bridge/Model/Event/OccurStatus.php, src/SWP/Component/Bridge/Model/Event/OccurStatusInterface.php, src/SWP/Component/Bridge/Model/EventInterface.php
=> Events mapping in bridge

AUTHORS.md, CONTRIBUTING.md, README.md, src/SWP/Bundle/BridgeBundle/README.md, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/README.md, src/SWP/Bundle/MultiTenancyBundle/README.md, src/SWP/Bundle/RuleBundle/README.md, src/SWP/Bundle/StorageBundle/README.md, src/SWP/Component/Bridge/README.md, src/SWP/Component/Common/README.md, src/SWP/Component/MultiTenancy/README.md, src/SWP/Component/Rule/README.md, src/SWP/Component/Storage/README.md, src/SWP/Component/TemplatesSystem/README.md
fixed
| Fixed tickets             | SWP-789
=> SWP-789 - Change url to the new RTD documentation

src/SWP/Bridge/JMSSerializerBundle/composer.json, src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/ContentListBundle/composer.json, src/SWP/Bundle/CoreBundle/composer.json, src/SWP/Bundle/FacebookInstantArticlesBundle/composer.json, src/SWP/Bundle/FixturesBundle/composer.json, src/SWP/Bundle/MenuBundle/composer.json, src/SWP/Bundle/MultiTenancyBundle/composer.json, src/SWP/Bundle/RuleBundle/composer.json, src/SWP/Bundle/SettingsBundle/composer.json, src/SWP/Bundle/StorageBundle/composer.json, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Bundle/UserBundle/composer.json, src/SWP/Component/Bridge/composer.json, src/SWP/Component/Common/composer.json, src/SWP/Component/ContentList/composer.json, src/SWP/Component/MultiTenancy/composer.json, src/SWP/Component/Revision/composer.json, src/SWP/Component/Rule/composer.json, src/SWP/Component/Storage/composer.json, src/SWP/Component/TemplatesSystem/composer.json
=> Increase dev version to 1.0-dev

src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleLoaderTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
| Fixed tickets             | internall missing feature report
=> [ContentBundle] add support for filtering article by keywords

src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Tests/Functional/SettingsTest.php
| Fixed tickets             | SWP-799
=> [CoreBundle] ass user setting for filtering preferences

app/Resources/meta/contentListItem.yml, docs/manual/templates_system/content_list.rst, docs/manual/templates_system/index.rst, src/SWP/Bundle/ContentBundle/Loader/PaginatedLoader.php, src/SWP/Bundle/ContentListBundle/Doctrine/ORM/ContentListItemRepository.php, src/SWP/Bundle/ContentListBundle/Loader/ContentListsItemLoader.php, src/SWP/Bundle/ContentListBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php, src/SWP/Bundle/CoreBundle/Pagination/Paginator.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListItemControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Loader/ContentListItemLoaderTest.php, src/SWP/Bundle/SettingsBundle/Controller/SettingsController.php, src/SWP/Component/ContentList/Model/ContentListItem.php, src/SWP/Component/ContentList/Model/ContentListItemInterface.php, src/SWP/Component/ContentList/Repository/ContentListItemRepositoryInterface.php
| Fixed tickets             | SWP-709
=> Add loader for content list items

src/SWP/Bundle/ContentBundle/Doctrine/ArticleRepositoryInterface.php, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php, src/SWP/Bundle/CoreBundle/Model/ArticlesCountInterface.php, src/SWP/Bundle/CoreBundle/Model/ArticlesCountTrait.php, src/SWP/Bundle/CoreBundle/Model/Route.php, src/SWP/Bundle/CoreBundle/Model/Tenant.php, src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.Route.yml, src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.Tenant.yml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Serializer/ArticlesCountHandler.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/RuleControllerTest.php
| Fixed tickets             | SWP-804
=> Add articles count to tenant and article api endpoints

src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/SettingsBundle/composer.json, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Bundle/UserBundle/Controller/UserController.php, src/SWP/Bundle/UserBundle/Form/Type/UserRolesType.php, src/SWP/Bundle/UserBundle/Tests/Functional/Controller/UserControllerTest.php, src/SWP/Bundle/UserBundle/composer.json
| Fixed tickets             | SWP-743
=> [UserBundle] add API to promote and demote users (add/remove user roles)

app/migrations/Version20170525105348.php, app/migrations/Version20170525105349.php, src/SWP/Bundle/CoreBundle/Model/User.php, src/SWP/Bundle/CoreBundle/Model/UserInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/User.orm.yml, src/SWP/Bundle/CoreBundle/Security/Authenticator/TokenAuthenticator.php, src/SWP/Bundle/CoreBundle/Tests/Controller/AuthControllerTest.php, src/SWP/Bundle/CoreBundle/spec/Model/UserSpec.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php
| Fixed tickets             | SWP-822
=> Use organization instead tenant in user entity

src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Serializer/ArticlesCountHandler.php
=> turn off tenantable filter when counting tenant articles

src/SWP/Bundle/CoreBundle/Controller/PackageController.php, src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php, src/SWP/Bundle/CoreBundle/Matcher/ArticleCriteriaMatcher.php, src/SWP/Bundle/CoreBundle/Tests/Functional/MultipleWebsitesPublish.php, src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/test/content_list.yml
| Fixed tickets             | SWP-839
=> fix adding article to content lists on publish

src/SWP/Bundle/CoreBundle/Controller/StaticThemeAssetsController.php, src/SWP/Bundle/MenuBundle/Resources/config/app/config.yml
=> add caching to static theme assets

CHANGELOG.md, app/migrations/Version20170608091640.php, src/SWP/Bundle/CoreBundle/Tests/Controller/OrganizationRuleControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/RuleControllerTest.php, src/SWP/Bundle/RuleBundle/Form/Type/RuleType.php, src/SWP/Bundle/RuleBundle/Resources/config/doctrine-orm/Rule.orm.yml, src/SWP/Bundle/RuleBundle/Resources/config/serializer/Model.Rule.yml, src/SWP/Bundle/RuleBundle/spec/Form/Type/RuleTypeSpec.php, src/SWP/Component/Rule/Model/Rule.php, src/SWP/Component/Rule/Model/RuleInterface.php, src/SWP/Component/Rule/spec/Model/RuleSpec.php
| Fixed tickets             | SWP-836
=> SWP-836 - Implement name and description in Organization Rules API

src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php, src/SWP/Bundle/CoreBundle/Repository/ContentListItemRepository.php, src/SWP/Bundle/CoreBundle/Repository/ContentListItemRepositoryInterface.php, src/SWP/Bundle/CoreBundle/Rule/Applicator/PackageRuleApplicator.php
| Fixed tickets             | SWP-858
=> SWP-858 - Content list issue when publishing item

src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Theme/TenantAwareThemeContext.php
=> don't try to fetch theme if tenant is not set in context

app/migrations/Version20170609104710.php, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleMedia.orm.yml
=> fixed usage_terms limit

src/SWP/Component/Bridge/Validator/NinjsValidator.php
=> allow additional properties in ninjs root

.travis.yml, src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Bundle/UserBundle/Model/User.php, src/SWP/Bundle/UserBundle/Tests/Functional/Controller/ProfileControllerTest.php
=> Allow removing about field content in user profile

docs/manual/templates_system/articles.rst, docs/manual/templates_system/index.rst, src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleLoaderTest.php, src/SWP/Bundle/MultiTenancyBundle/composer.json, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Bundle/UserBundle/composer.json
| Fixed tickets             | SWP-807
=> allow multiple routes filtering in articles loader

install.md, src/SWP/Bundle/ContentBundle/Tests/Functional/app/ContentBundle/config.yml, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/TemplatesSystemBundle/Tests/Functional/app/TemplatesSystem/config.yml
| Fixed tickets             | SWP-881
=> [CoreBundle] add two new user settings

CHANGELOG.md, INSTALL.md, README.md, composer.json, src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/ContentListBundle/composer.json, src/SWP/Bundle/CoreBundle/composer.json, src/SWP/Bundle/ElasticSearchBundle/composer.json, src/SWP/Bundle/FacebookInstantArticlesBundle/composer.json, src/SWP/Bundle/FixturesBundle/composer.json, src/SWP/Bundle/MenuBundle/composer.json, src/SWP/Bundle/MultiTenancyBundle/composer.json, src/SWP/Bundle/RuleBundle/composer.json, src/SWP/Bundle/SettingsBundle/composer.json, src/SWP/Bundle/StorageBundle/composer.json, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Bundle/UserBundle/composer.json, src/SWP/Component/Bridge/composer.json, src/SWP/Component/Common/composer.json, src/SWP/Component/ContentList/composer.json, src/SWP/Component/MultiTenancy/composer.json, src/SWP/Component/Revision/composer.json, src/SWP/Component/Rule/composer.json, src/SWP/Component/Storage/composer.json, src/SWP/Component/TemplatesSystem/composer.json
=> Set new dev-master version, improve changelog and installation notes

app/config/security.yml, docs/internal_api/authentication.rst, src/SWP/Bundle/CoreBundle/Controller/AuthController.php, src/SWP/Bundle/CoreBundle/EventListener/ActivateLivesiteEditorListener.php, src/SWP/Bundle/CoreBundle/Model/ApiKey.php, src/SWP/Bundle/CoreBundle/Model/ApiKeyInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Security/Authenticator/TokenAuthenticator.php, src/SWP/Bundle/CoreBundle/Tests/Controller/AuthControllerTest.php
| Fixed tickets             | SWP-889, SWP-890
=> [CoreBundle] Generate Authentication URL API, LivesiteEditor activator (by cookie

app/config/routing.yml, src/SWP/Bundle/CoreBundle/Controller/RedirectingController.php, src/SWP/Bundle/CoreBundle/Tests/Controller/RedirectingControllerTest.php
…ailing slash to versions without it
| Fixed tickets             | SWP-882
=> add redirecting controller and redirect GET request to routes with trailing slash to versions without it

CHANGELOG.md, app/Resources/meta/contentList.yml, docs/manual/templates_system/content_list.rst, src/SWP/Bundle/ContentListBundle/Loader/ContentListLoader.php, src/SWP/Bundle/ContentListBundle/Loader/ContentListsItemLoader.php, src/SWP/Bundle/ContentListBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Loader/ContentListLoaderTest.php
| Fixed tickets             | SWP-892
=> add content lists loader with docs and tests

app/migrations/Version20170802191728.php, src/SWP/Bundle/ContentListBundle/Loader/ContentListLoader.php, src/SWP/Bundle/CoreBundle/Controller/OrganizationRuleController.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/ApiKey.orm.yml, src/SWP/Bundle/CoreBundle/Security/Authenticator/TokenAuthenticator.php
| Fixed tickets             | SWP-911
=> Fix content loader when wrong parameter is passed, improve api key index

src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php, src/SWP/Bundle/CoreBundle/Tests/Controller/RegistrationControllerTest.php, src/SWP/Bundle/UserBundle/Form/Type/RegistrationFormType.php
| Fixed tickets             | SWP-902
=> Add validation groups to custom registration form

src/SWP/Bundle/CoreBundle/Tests/Controller/MenuControllerTest.php, src/SWP/Bundle/MenuBundle/Manager/MenuItemManager.php, src/SWP/Bundle/MenuBundle/spec/Manager/MenuItemManagerSpec.php
| Fixed tickets             | SWP-905
=> allow to move menu item to new empty parent

CHANGELOG.md, src/SWP/Bundle/CoreBundle/Controller/PackageController.php, src/SWP/Bundle/CoreBundle/Form/Type/PackageType.php, src/SWP/Bundle/CoreBundle/Service/ArticlePublisher.php, src/SWP/Bundle/CoreBundle/Tests/Controller/PackageControllerTest.php
| Fixed tickets             | SWP-852
=> Add API endpoint for package update (pubStatus)

src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/public/dist/all.js, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/public/js/scripts/onload.js
corrected (demo theme)
| Fixed tickets             | SWP-919
=> SWP-919 - Correction for login script on demo themes

CHANGELOG.md, src/SWP/Bundle/CoreBundle/Controller/WidgetController.php, src/SWP/Bundle/CoreBundle/Tests/Controller/WidgetControllerTest.php, src/SWP/Bundle/CoreBundle/Theme/TenantAwareThemeContext.php
| Fixed tickets             | SWP-872
=> Add API endpoint for listing available widgets templates in current theme

app/SymfonyRequirements.php, composer.lock, src/SWP/Bundle/CoreBundle/Checker/AmpSupportChecker.php, src/SWP/Bundle/CoreBundle/Controller/PackagePreviewController.php, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideArticleBodyProcessorPass.php, src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php, src/SWP/Bundle/CoreBundle/EventListener/PreviewModeListener.php, src/SWP/Bundle/CoreBundle/Model/Article.php, src/SWP/Bundle/CoreBundle/Model/ArticleInterface.php, src/SWP/Bundle/CoreBundle/Processor/ArticleBodyProcessor.php, src/SWP/Bundle/CoreBundle/Processor/ArticleBodyProcessorInterface.php, src/SWP/Bundle/CoreBundle/Request/ParamConverter/ResolveEntityParamConverter.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/SWPCoreBundle.php, src/SWP/Bundle/CoreBundle/Tests/Functional/PackagePreviewTest.php, src/SWP/Bundle/CoreBundle/Theme/AmpThemeLoader.php
| Fixed tickets             | SWP-823
TODO:
=> fix package preview in amp mode

src/SWP/Bundle/CoreBundle/Fragment/ExternalFragmentRenderer.php, src/SWP/Bundle/CoreBundle/Tests/Fragment/ExternalFragmentRendererTest.php, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/views/liveblog.html.twig
| Fixed tickets             | SWP-915
=> add liveblog template to demo theme

src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/AddCustomTwigCachePass.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/SWPCoreBundle.php, src/SWP/Bundle/CoreBundle/Tests/Twig/TenantAwareCacheTest.php, src/SWP/Bundle/CoreBundle/Twig/Cache/TenantAwareCache.php
| Fixed tickets             | SWP-910
TODO:
=> add tenant aware twig cache

app/AppKernel.php, app/config/config.yml, app/config/parameters.yml.dist, composer.json, composer.lock, nohup.out, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Tests/Twig/StringyExtensionTest.php, src/SWP/Bundle/CoreBundle/Twig/StringyExtension.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/ContainerNodeTest.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/GimmeListNodeTest.php, src/SWP/Component/TemplatesSystem/Twig/Extension/ContainerExtension.php, src/SWP/Component/TemplatesSystem/Twig/Node/ContainerNode.php, src/SWP/Component/TemplatesSystem/Twig/Node/GimmeListNode.php, src/SWP/Component/TemplatesSystem/Twig/Node/GimmeNode.php, web/app.php, web/app_dev.php
=> upgrade symfony to 3.3 release, fix depreceations, use twig 2.0

app/config/parameters_test.yml, src/SWP/Bundle/CoreBundle/Controller/ThemesController.php, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OrganizationThemesProviderPass.php, src/SWP/Bundle/CoreBundle/Form/Type/ThemeUploadType.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/SWPCoreBundle.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ThemeControllerTest.php, src/SWP/Bundle/CoreBundle/Theme/Locator/OrganizationThemesRecursiveFileLocator.php, src/SWP/Bundle/CoreBundle/Theme/Uploader/TenantAwareThemeUploader.php, src/SWP/Bundle/CoreBundle/Theme/Uploader/ThemeUploaderInterface.php
| Fixed tickets             | SWP-934 SWP-935
=> [feature] add api to upload and list themes in organization

src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideArticleSourceAdderPass.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/SWPCoreBundle.php, src/SWP/Bundle/CoreBundle/Service/TenantAwareArticleSourcesAdder.php, src/SWP/Bundle/CoreBundle/Tests/Functional/ArticleSourcesTest.php, src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleLoaderTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
This pr makes sure each tenant can access its own sources, it should not access sources of other tenants or other organizations.
=> Article sources fixes

src/SWP/Bundle/CoreBundle/Controller/ThemesController.php
=> fixed theme install documentation typo

.travis.yml, app/migrations/Version20170301172303.php, app/migrations/Version20170829142821.php, app/migrations/Version20170908083733.php, app/migrations/Version20170908085421.php, src/SWP/Bundle/FixturesBundle/AbstractFixture.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadWidgetsData.php, src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/dev/tenant.yml, src/SWP/Bundle/SettingsBundle/composer.json, src/SWP/Bundle/UserBundle/composer.json, src/SWP/Component/MultiTenancy/Model/TenantInterface.php
| Fixed tickets             | SWP-779
=> add missing migrations

src/SWP/Bundle/SettingsBundle/composer.json, src/SWP/Bundle/UserBundle/composer.json
=> set lower version of symfony translation component

src/SWP/Bundle/ContentBundle/Service/ArticleSourceService.php, src/SWP/Bundle/ContentBundle/Service/ArticleSourcesAdder.php, src/SWP/Bundle/CoreBundle/EventListener/UpdatedPackageListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Service/ArticlePublisher.php, src/SWP/Bundle/CoreBundle/Tests/Functional/MultipleWebsitesPublish.php, src/SWP/Bundle/SettingsBundle/composer.json, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Bundle/UserBundle/composer.json
=> fix articles handling after correction

src/SWP/Bundle/CoreBundle/Controller/StaticThemeAssetsController.php, src/SWP/Bundle/CoreBundle/Tests/Controller/StaticThemeAssetsControllerTest.php
=> allow to load all files from theme public/ root dir

app/config/config.yml, src/SWP/Bundle/CoreBundle/Controller/StaticThemeAssetsController.php, src/SWP/Bundle/CoreBundle/Tests/ServicesTest.php, src/SWP/Bundle/CoreBundle/Theme/Configuration/TenantableConfigurationSourceFactory.php, src/SWP/Bundle/CoreBundle/Theme/Locator/TenentThemesRecursiveFileLocator.php
=> follow symlinks in theme locator, fix wrong cache adapter initialization

composer.json, composer.lock, docs/themes.rst, src/SWP/Component/Bridge/Validator/NinjsValidator.php, src/SWP/Component/Bridge/composer.json
=> update justinrainbow/json-schema in bridge

src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/ContentListBundle/composer.json, src/SWP/Bundle/CoreBundle/composer.json, src/SWP/Bundle/ElasticSearchBundle/composer.json, src/SWP/Bundle/FacebookInstantArticlesBundle/composer.json, src/SWP/Bundle/FixturesBundle/composer.json, src/SWP/Bundle/MenuBundle/composer.json, src/SWP/Bundle/MultiTenancyBundle/composer.json, src/SWP/Bundle/RuleBundle/composer.json, src/SWP/Bundle/SettingsBundle/composer.json, src/SWP/Bundle/StorageBundle/composer.json, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Bundle/UserBundle/composer.json, src/SWP/Component/Bridge/composer.json, src/SWP/Component/Common/composer.json, src/SWP/Component/ContentList/composer.json, src/SWP/Component/MultiTenancy/composer.json, src/SWP/Component/Revision/composer.json, src/SWP/Component/Rule/composer.json, src/SWP/Component/Storage/composer.json, src/SWP/Component/TemplatesSystem/composer.json
=> update dev version of packages to 1.2-dev

src/SWP/Bridge/JMSSerializerBundle/composer.json, src/SWP/Bundle/BridgeBundle/composer.json
| Bug fix?                  | |no
=> use latest common in bridge

src/SWP/Bundle/CoreBundle/Service/RevisionAwareContainerService.php, src/SWP/Bundle/CoreBundle/Tests/Controller/RevisionControllerTest.php
=> Don't detach container on forking

composer.json, composer.lock, src/SWP/Bundle/CoreBundle/Command/ThemeSetupCommand.php, src/SWP/Bundle/CoreBundle/Tests/Command/ThemeSetupCommandTest.php
=> add option to activate installed theme

app/config/parameters_test.yml, app/migrations/Version20170301172303.php, app/phpunit.xml.dist, src/SWP/Bundle/CoreBundle/Tests/AmpHtmlTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/AuthControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Functional/ArticleSourcesTest.php, src/SWP/Bundle/CoreBundle/Tests/Functional/MultipleWebsitesPublish.php, src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/test/tenant.yml, src/SWP/Bundle/MultiTenancyBundle/Command/CreateTenantCommand.php
=> use domain env instead domain param

src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php, src/SWP/Bundle/ContentBundle/Model/RouteInterface.php, src/SWP/Bundle/ContentBundle/Provider/ORM/RouteProvider.php, src/SWP/Bundle/ContentBundle/Service/RouteService.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/RouteControllerTest.php, src/SWP/Bundle/ContentBundle/spec/Service/RouteServiceSpec.php, src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php, src/SWP/Bundle/CoreBundle/Model/Route.php, src/SWP/Bundle/CoreBundle/Tests/ContentPushTest.php
=> remove slash from allowed chars in slug, change routes loading order test child routes first, add tests

composer.lock
=> update vendors to latest stable

src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php
=> internally cache route defaults in enhancer

CHANGELOG.md, src/SWP/Bundle/ContentBundle/Processor/ArticleBodyProcessor.php, src/SWP/Bundle/ContentBundle/Tests/Functional/EventListener/ProcessArticleMediaListenerTest.php
| Fixed tickets             | SWP-879
=> fixed body images are losing alt attribute

composer.json, features/packages/get_package_from_api.feature, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Package.yml
| Fixed tickets             | SWP-1021
=> [SWP-1021] Add createdAt to package response

features/02_articles/searching_articles_by_authors.feature, features/bootstrap/FeatureContext.php, src/SWP/Bundle/ElasticSearchBundle/Resources/config/app/config.yml
=> fix searching articles by author

src/SWP/Component/MultiTenancy/Resolver/TenantResolver.php, src/SWP/Component/MultiTenancy/spec/Resolver/TenantResolverSpec.php
| BC breaks?                | no? have hope
| Tests pass?               | yes|
| Fixed tickets             | SWP-857
=> ignore www prefix in theme resolver

docs/components/TemplatesSystem/features/customTags/gimmelist.rst
| Fixed tickets             | SWP-1036
=> improved filtering articles by authors docs

src/SWP/Bundle/CoreBundle/Provider/ThemeSettingsProvider.php, src/SWP/Bundle/SettingsBundle/Tests/Functional/Manager/SettingsManagerTest.php
| Fixed tickets             | SWP-1055
=> Make settings property optional in theme.json

CHANGELOG.md, app/Resources/meta/author.yml, docs/manual/templates_system/article_author.rst, docs/manual/templates_system/index.rst, src/SWP/Bundle/ContentBundle/Doctrine/ArticleAuthorRepositoryInterface.php, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleAuthorRepository.php, src/SWP/Bundle/ContentBundle/Loader/ArticleAuthorLoader.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleAuthorLoaderTest.php, src/SWP/Bundle/CoreBundle/Tests/Loader/ContentListLoaderTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
| Fixed tickets             | SWP-1044
=> added loader for article authors

src/SWP/Bundle/ContentBundle/EventListener/UpdatePackageAuthorsListener.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml
=> fixed duplicated authors persisting

src/SWP/Bundle/CoreBundle/Form/Type/ThemeUploadType.php
=> Increase theme zip file upload limit to 10MB

.travis.yml, CHANGELOG.md, INSTALL.md, app/AppKernel.php, composer.json, composer.lock, docs/manual/templates_system/templates_features.rst, docs/reference/twig_extensions.rst, features/twig/redirects_from_remplate.feature, scripts/supervisor/supervisor_analytics.conf, scripts/supervisor/supervisor_webhooks.conf, src/SWP/Bundle/ContentBundle/Controller/RouteController.php, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/404_redirect.html.twig, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/route_with_301_redirect.html.twig, src/SWP/Bundle/TemplatesSystemBundle/EventListener/RedirectListener.php, src/SWP/Bundle/TemplatesSystemBundle/Resources/config/services.yml, src/SWP/Bundle/TemplatesSystemBundle/Twig/Extension/RedirectExtension.php, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Component/TemplatesSystem/Twig/Extension/ContainerExtension.php, supervisor.md
Needed to handle properly missing data loaded by loader in template.
=> add redirect_extension with option to redirect to other route or 404 page

CHANGELOG.md, UPGRADE.md, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Component/TemplatesSystem/composer.json
raise required twig version in templates system, update CHANGELOG and add UPGRADE instructions
=> Before release improvements and cleaning

CHANGELOG.md, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/ThemesControllerTest.php, src/SWP/Bundle/CoreBundle/Theme/Asset/AssetsInstaller.php, src/SWP/Bundle/CoreBundle/Theme/Installer/TenantAwareThemeInstaller.php
| Fixed tickets             | SWP-1093
=> install assets when theme is installed

CHANGELOG.md, src/SWP/Bundle/CoreBundle/Model/WidgetModel.php, src/SWP/Bundle/CoreBundle/Widget/TemplateWidgetHandler.php, src/SWP/Bundle/CoreBundle/spec/Widget/TemplateWidgetHandlerSpec.php
| Fixed tickets             | SWP-415
=> Added template widget

UPGRADE.md, app/config/config_dev.yml, composer.lock, src/SWP/Bundle/ContentBundle/Tests/Functional/Loader/ArticleLoaderTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Loader/ArticleMediaLoaderTest.php, src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php, src/SWP/Component/TemplatesSystem/Gimme/Context/Context.php, src/SWP/Component/TemplatesSystem/Gimme/Meta/Meta.php
=> add upgrade instructions

src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Provider/ORM/RouteProvider.php, src/SWP/Bundle/ContentBundle/Provider/RouteProviderInterface.php, src/SWP/Bundle/CoreBundle/EventListener/RemoveItemsListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListControllerTest.php
| New feature?              | improvement
| Fixed tickets             | SWP-1098
=> allow filtering by route name in content lists

app/config/parameters.yml.dist, src/SWP/Bundle/ElasticSearchBundle/Resources/config/app/config.yml
| Fixed tickets             | SWP-1101
- added support for custom elasticsearch index name per Publisher instance
- ES bundle config adjustments: Cannot find corresponding Doctrine objects for all Elastica results
The ES index needs to be repopulated.
=> ES config improvements

app/migrations/Version20180330092724.php, composer.json, composer.lock, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Package.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.BaseContent.yml
| Bug fix?                  | yes/no
=> add missing ednote to package in db

composer.json, composer.lock, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleAuthorRepository.php, src/SWP/Bundle/ContentBundle/Loader/ArticleAuthorLoader.php, src/SWP/Bundle/ContentBundle/Loader/ArticleMediaLoader.php, src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleAuthorLoaderTest.php, src/SWP/Bundle/StorageBundle/Doctrine/ORM/EntityRepositoryTrait.php
=> Fix article author loaders (sorting) and article media loader (cache key)

docs/cookbooks/developers/widgets.rst
=> template widget docu

.travis.yml, app/config/config.yml, app/config/config_test.yml, composer.json, composer.lock, src/SWP/Bundle/CoreBundle/Locator/ApplicationResourceLocator.php, src/SWP/Bundle/CoreBundle/Locator/BundleResourceLocator.php, src/SWP/Bundle/CoreBundle/Theme/Asset/AssetsInstaller.php, src/SWP/Bundle/CoreBundle/Theme/Asset/PathResolver.php, src/SWP/Bundle/CoreBundle/Theme/Configuration/TenantableConfigurationProvider.php, src/SWP/Bundle/CoreBundle/Theme/Configuration/TenantableConfigurationSourceFactory.php, src/SWP/Bundle/CoreBundle/Theme/Factory/ThemeFactory.php, src/SWP/Bundle/CoreBundle/Theme/Loader/TenantAwareThemeLoader.php, src/SWP/Bundle/CoreBundle/Theme/Locator/OrganizationThemesRecursiveFileLocator.php, src/SWP/Bundle/CoreBundle/Theme/Locator/TenentThemesRecursiveFileLocator.php, src/SWP/Bundle/CoreBundle/Theme/Repository/ReloadableInMemoryRepository.php, src/SWP/Bundle/CoreBundle/Theme/TenantAwareThemeContext.php, src/SWP/Bundle/CoreBundle/spec/Theme/Asset/PathResolverSpec.php, src/SWP/Bundle/CoreBundle/spec/Theme/TenantAwareThemeContextSpec.php, src/SWP/Bundle/UserBundle/Resources/config/routing.yml
| Bug fix?                  | yes - in deps
=> Update dependencies on master

src/SWP/Bundle/CoreBundle/Command/ThemeSetupCommand.php, src/SWP/Bundle/CoreBundle/Model/Article.php, src/SWP/Bundle/CoreBundle/Tests/Command/ThemeSetupCommandTest.php, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes_to_be_installed/theme_test_install_with_broken_theme_json/theme.json, src/SWP/Bundle/CoreBundle/Theme/Generator/FakeArticlesGenerator.php, src/SWP/Bundle/CoreBundle/Theme/Generator/ThemeRoutesGenerator.php, src/SWP/Bundle/CoreBundle/Theme/Installer/TenantAwareThemeInstaller.php, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/theme.json, src/SWP/Bundle/UserBundle/.travis.yml
| Fixed tickets             | SWP-1062
=> revert copied theme in case of installation error

src/SWP/Bundle/CoreBundle/Command/ThemeSetupCommand.php, src/SWP/Bundle/CoreBundle/Controller/ThemesController.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/ThemesControllerTest.php, src/SWP/Bundle/CoreBundle/Theme/Installer/TenantAwareThemeInstaller.php, src/SWP/Bundle/CoreBundle/Theme/Installer/ThemeInstallerInterface.php, src/SWP/Bundle/CoreBundle/Theme/Service/ThemeService.php, src/SWP/Bundle/CoreBundle/Theme/Service/ThemeServiceInterface.php, src/SWP/Bundle/CoreBundle/Theme/Uploader/OrganizationAwareThemeUploader.php, src/SWP/Bundle/CoreBundle/Theme/Uploader/ThemeUploaderInterface.php
=> move shared between command and api logic to service

src/SWP/Bundle/ContentBundle/Provider/ORM/RouteProvider.php, src/SWP/Bundle/ContentBundle/Provider/RouteProviderInterface.php, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes_to_be_installed/theme_test_install_with_generated_data/theme.json, src/SWP/Bundle/CoreBundle/Theme/Generator/ThemeRoutesGenerator.php
| Fixed tickets             | SWP-1105
=> check if route exists by name, improve test

docs/cookbooks/implementators/secure_content_push.rst, src/SWP/Bundle/CoreBundle/Command/ThemeSetupCommand.php, src/SWP/Bundle/CoreBundle/Theme/Generator/ThemeWidgetsGenerator.php
| Deprecations?             | |no
=> improve codestyle, docsblocks, and docs

features/settings/listing_settings.feature, features/settings/restoring_settings_by_scope.feature, features/settings/updating_multiple_settings_at_once.feature, features/themes/listing_theme_settings.feature, features/themes/listing_theme_settings_when_updated_by_different_tenants.feature, features/themes/updating_boolean_setting.feature, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/theme.json, src/SWP/Bundle/SettingsBundle/Form/Type/SettingType.php, src/SWP/Bundle/SettingsBundle/Manager/SettingsManager.php, src/SWP/Bundle/SettingsBundle/Model/Settings.php, src/SWP/Bundle/SettingsBundle/Model/SettingsInterface.php, src/SWP/Bundle/SettingsBundle/Resources/config/serializer/Model.Settings.yml
=> fixed boolean values in settings

src/SWP/Bundle/CoreBundle/Theme/Provider/ThemeProvider.php
=> fix themes processing when loaded multiple time during one request (case of api/doc)

CHANGELOG.md, features/02_articles/validating_article_slugline.feature, src/SWP/Bundle/ContentBundle/Model/Article.php
| Fixed tickets             | SWP-1126
=> Not possible to publish article when the slug contains chinese chars

app/SymfonyRequirements.php, features/tenants/creating_a_new_tenant.feature, src/SWP/Bundle/ContentBundle/Controller/ArticleController.php, src/SWP/Bundle/ContentBundle/Controller/RouteController.php, src/SWP/Bundle/CoreBundle/Controller/ArticleSourceController.php, src/SWP/Bundle/CoreBundle/Controller/ContainerController.php, src/SWP/Bundle/CoreBundle/Controller/ContentListController.php, src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php, src/SWP/Bundle/CoreBundle/Controller/CurrentThemeController.php, src/SWP/Bundle/CoreBundle/Controller/OrganizationRuleController.php, src/SWP/Bundle/CoreBundle/Controller/PackageController.php, src/SWP/Bundle/CoreBundle/Controller/RuleController.php, src/SWP/Bundle/CoreBundle/Controller/TenantController.php, src/SWP/Bundle/CoreBundle/Controller/WebhookController.php, src/SWP/Bundle/CoreBundle/Controller/WidgetController.php, src/SWP/Bundle/SettingsBundle/Controller/SettingsController.php
| Fixed tickets             | SWP-1128
=> remove invalid cache headers from api resources

features/settings/updating_multiple_settings_at_once.feature, src/SWP/Bundle/SettingsBundle/Form/Type/SettingType.php, src/SWP/Bundle/SettingsBundle/Manager/SettingsManager.php, src/SWP/Bundle/SettingsBundle/Tests/Functional/Controller/SettingsControllerTest.php
=> properly handle int values in settings

src/SWP/Bundle/CoreBundle/Theme/Generator/FakeArticlesGenerator.php
Edge case with array cache and clean install. Fixed also in master (before)
| Fixed tickets             | reported by Marko
=> [1.3] fix fake articles generator (persist article before article statistics)

src/SWP/Bundle/CoreBundle/Command/ThemeSetupCommand.php, src/SWP/Bundle/CoreBundle/Theme/Service/ThemeService.php, src/SWP/Bundle/CoreBundle/Theme/Service/ThemeServiceInterface.php, src/SWP/Bundle/CoreBundle/Theme/TenantAwareThemeContext.php, src/SWP/Bundle/CoreBundle/Theme/TenantAwareThemeContextInterface.php
=> set new theme in tenant if activate it set to true but no generation data to false

features/content_push/checking_secured_content_push.feature, src/SWP/Bundle/CoreBundle/EventListener/SecuredContentPushListener.php
=> [fix] run signature check only for content/assets push requests

features/preview/preview_article_when_fake_template_is_set.feature, src/SWP/Bundle/CoreBundle/Controller/PackagePreviewController.php
Fixes for package preview in targeted publishing. Always fallback to default template.
=> preview fixes

app/Resources/meta/author.yml, src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleAuthorLoaderTest.php
| Fixed tickets             | SWP-1142
=> [improvement][SWP-1141] add slug property to author meta

src/SWP/Bundle/CoreBundle/Service/ArticlePublisher.php
=> dispatch publish after post_update

src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/ContentPushControllerTest.php, src/SWP/Component/Bridge/Model/BaseContent.php, src/SWP/Component/Bridge/Model/ContentInterface.php, src/SWP/Component/Bridge/spec/Model/BaseContentSpec.php
=> [improvement] allow to get array of services names and codes in rules

CHANGELOG.md, app/migrations/Version20180605111249.php, features/packages/creating_package_with_authors.feature, src/SWP/Bundle/ContentBundle/EventListener/PopulateArticleAuthorSlugListener.php, src/SWP/Bundle/ContentBundle/Model/ArticleAuthor.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml
| Fixed tickets             | SWP-1168
=>  Authors without slug after publishing article

features/packages/publish_package_with_backward_published_date.feature, src/SWP/Bundle/ContentBundle/EventListener/SetProvidedPublishedDateListener.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml, src/SWP/Bundle/ContentBundle/Service/ArticleService.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/ArticleControllerTest.php, src/SWP/Bundle/CoreBundle/Adapter/WordpressAdapter.php
=> handle imported articles published at date

app/migrations/Version20180605111249.php, src/SWP/Bundle/BridgeBundle/Tests/Functional/BridgeTest.php
=> [Fix] migration script

CHANGELOG.md, features/02_articles/article_unpublishing.feature, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Functional/ArticleUnpublishFromThemeGeneratedDataTest.php, src/SWP/Bundle/CoreBundle/Tests/Theme/Generator/FakeArticlesGeneratorTest.php, src/SWP/Bundle/CoreBundle/Theme/Generator/FakeArticlesGenerator.php, src/SWP/Bundle/CoreBundle/Theme/TenantAwareThemeContext.php
| Fixed tickets             | SWP-1169
Failing Bridge Bundle tests will be fixed in the next PR
=> API endpoint to patch article not working

src/SWP/Bundle/CoreBundle/WebSocket/Topic/AbstractSecuredTopic.php
=> check for connection in AbstractSecuredTopic.php

CHANGELOG.md, features/packages/creating_package_with_authors.feature, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Author.yml, src/SWP/Bundle/ContentBundle/Controller/MediaController.php, src/SWP/Bundle/ContentBundle/EventListener/UpdatePackageAuthorsListener.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideMediaManagerPass.php, src/SWP/Bundle/CoreBundle/EventListener/DownloadArticleAuthorAvatarListener.php, src/SWP/Bundle/CoreBundle/Manager/AuthorMediaManager.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Command/ThemeSetupCommandTest.php, src/SWP/Bundle/CoreBundle/Theme/Generator/FakeArticlesGenerator.php, src/SWP/Bundle/CoreBundle/Theme/Service/ThemeService.php
=> store provided article author images locally

src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php
=> set updated at when package is updated

src/SWP/Bundle/CoreBundle/EventSubscriber/ProcessOrganizationRulesSubscriber.php
| Fixed tickets             | SWP-1191
=> Undefined route after publishing by target rules

CHANGELOG.md, src/SWP/Bundle/CoreBundle/Repository/ContentListItemRepository.php, src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/test/content_list_item.yml, src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/test/list_content.yml
| Fixed tickets             | SWP-1192
=> List only published articles in content lists on frontend

src/SWP/Bundle/ContentBundle/Routing/MediaRouter.php
=> [fix] remove debuging code

features/targeted_publishing/evaluate_based_on_package_service.feature, src/SWP/Bundle/CoreBundle/Matcher/RulesMatcher.php
=> fixed rules evaluation on package services

src/SWP/Bundle/ContentBundle/Controller/RouteController.php
=> fix spelling

src/SWP/Bundle/AnalyticsBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
=> use instance secret code for queue name

src/SWP/Bundle/ContentBundle/Model/ArticleAuthor.php, src/SWP/Bundle/ContentBundle/Model/ArticleAuthorInterface.php
=> fix article author interface

src/SWP/Bundle/CoreBundle/Theme/Model/Theme.php, src/SWP/Bundle/CoreBundle/Theme/Model/ThemeInterface.php
| Fixed tickets             | SWP-1200
=> implement serializable interface in Theme class

app/config/config.yml, src/SWP/Bundle/CoreBundle/Context/CachedTenantContext.php, src/SWP/Bundle/CoreBundle/EventListener/TenantNotFoundExceptionListener.php, src/SWP/Bundle/CoreBundle/EventListener/TenantRevisionListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/TenantControllerTest.php, src/SWP/Component/MultiTenancy/Exception/TenantNotFoundException.php
| BC breaks?                | ?no
=> Show real error when tenant is not found

features/preview/preview_article_based_on_package_data.feature, src/SWP/Bundle/ContentBundle/EventListener/PopulateArticleAuthorSlugListener.php, src/SWP/Bundle/ContentBundle/Processor/ArticleAuthorProcessor.php, src/SWP/Bundle/CoreBundle/Service/ArticlePreviewer.php, src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/swp__test-theme/views/article.html.twig, src/SWP/Bundle/CoreBundle/Tests/Functional/PackagePreviewTest.php
=> process article author slug in preview

app/config/config_dev.yml, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
| Fixed tickets             | comma separated list of tickets fixed by the PR
=> move dev dependecies config to dev files

.travis.yml, app/config/config_test.yml, app/config/parameters_test.yml, src/SWP/Bundle/FixturesBundle/WebTestCase.php
| Fixed tickets             | SWP-1173
=> [Maintenance] test migrations on postgres

CHANGELOG.md, docs/cookbooks/developers/paywall.rst, docs/cookbooks/developers/rules.rst, features/paywall/marking_article_as_paywall_secured_by_rule.feature, features/paywall/marking_article_as_paywall_secured_on_package_publish.feature, features/targeted_publishing/creating_a_new_publishing_destination.feature, src/SWP/Bundle/CoreBundle/Form/Type/PublishDestinationType.php, src/SWP/Bundle/CoreBundle/Model/PublishDestination.php, src/SWP/Bundle/CoreBundle/Model/PublishDestinationInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/rules.yml, src/SWP/Bundle/CoreBundle/Rule/Applicator/PaywallSecuredRuleApplicator.php, src/SWP/Bundle/CoreBundle/Service/ArticlePublisher.php
| Fixed tickets             | SWP-1246
=> Allow to mark articles as paywall-secured via rules and destinations

.travis.yml, app/config/behat_test.yml, app/config/config_test.yml, app/config/security.yml, app/phpunit.xml.dist, features/bootstrap/FeatureContext.php, features/user/register_and_login.feature, src/SWP/Behat/Service/TokenGeneratorStub.php, src/SWP/Bundle/CoreBundle/Controller/AuthController.php, src/SWP/Bundle/CoreBundle/Security/Authenticator/TokenAuthenticator.php, src/SWP/Bundle/CoreBundle/Tests/Controller/AuthControllerTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php, src/SWP/Bundle/UserBundle/Controller/ProfileController.php, src/SWP/Bundle/UserBundle/Controller/RegistrationController.php
| Fixed tickets             | SWP-1230
=> don't set INTERNAL_API Role for all users, add tests for user (reader) handling

src/SWP/Bundle/CoreBundle/Tests/Controller/TenantControllerTest.php
=> [tests] add tests for articles count handler

src/SWP/Bundle/CoreBundle/Adapter/WordpressAdapter.php, src/SWP/Bundle/CoreBundle/EventSubscriber/ProcessArticleRulesSubscriber.php, src/SWP/Bundle/CoreBundle/Tests/ContentPushTest.php
=> fix wordpress adapter create and publish at this same time handling

src/SWP/Bundle/CoreBundle/Processor/RulesProcessor.php
=> check if tenant is set

src/SWP/Bundle/CoreBundle/Controller/TenantController.php, src/SWP/Bundle/CoreBundle/Tests/Controller/TenantControllerTest.php
| Tests pass?               | no
| Fixed tickets             | SWP-1256
=> [fix] change tenant context to the one scheduled for remove before asking for his articles

docs/manual/templates_system/content_list.rst, src/SWP/Bundle/ContentListBundle/Loader/ContentListsItemLoader.php, src/SWP/Bundle/CoreBundle/Tests/Loader/ContentListItemLoaderTest.php
| Fixed tickets             | SWP-1287
=> use content list meta for fetching content list items

src/SWP/Bundle/CoreBundle/Adapter/WordpressAdapter.php, src/SWP/Bundle/CoreBundle/Processor/RulesProcessor.php, src/SWP/Bundle/CoreBundle/Tests/Adapter/WordpressAdapterTest.php
=> cache failed requests to wordpress instance

src/SWP/Bundle/CoreBundle/Controller/TenantController.php, src/SWP/Bundle/CoreBundle/Tests/Controller/TenantControllerTest.php
=> add option to force remove tenant

src/SWP/Bundle/CoreBundle/Adapter/WordpressAdapter.php
=> [hotfix] disable wordpress tags handling

src/SWP/Bundle/CoreBundle/Tests/Controller/TenantControllerTest.php
=> [test fix] change subdomain name for test tenant

app/migrations/Version20180821140705.php
| Fixed tickets             | SWP-1305
=> set default value for paywall secured column

app/config/config.yml, src/SWP/Bundle/CoreBundle/Adapter/WordpressAdapter.php, src/SWP/Bundle/CoreBundle/Command/CreateTenantCommand.php, src/SWP/Bundle/CoreBundle/Context/CachedTenantContext.php, src/SWP/Bundle/CoreBundle/Controller/TenantController.php, src/SWP/Bundle/CoreBundle/EventListener/CustomPublisherHeaderListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Adapter/WordpressAdapterTest.php, src/SWP/Bundle/CoreBundle/Tests/Command/CreateTenantCommandTest.php, src/SWP/Bundle/CoreBundle/Theme/Service/ThemeService.php, src/SWP/Bundle/CoreBundle/Theme/TenantAwareThemeContext.php
| Fixed tickets             | SWP-1303
=> don't throw tenant not found when profiler is collecting info about themes

docs/manual/templates_system/routes.rst, src/SWP/Bundle/ContentBundle/Loader/RouteLoader.php, src/SWP/Bundle/CoreBundle/Twig/MenuExtension.php
| Fixed tickets             | SWP-1304
=> add missing return to get function, fix docs for routes loader

.travis.yml, features/routes/management.feature, src/SWP/Bundle/ContentBundle/Controller/RouteController.php, src/SWP/Bundle/ContentBundle/Doctrine/ORM/RouteRepository.php, src/SWP/Bundle/ContentBundle/Form/Type/RouteType.php, src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.Route.yml, src/SWP/Bundle/ContentBundle/Resources/config/services.yml, src/SWP/Bundle/ContentBundle/Service/RouteService.php, src/SWP/Bundle/ContentBundle/Service/RouteServiceInterface.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/RouteControllerTest.php, src/SWP/Bundle/ContentBundle/spec/Service/RouteServiceSpec.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Route.orm.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListItemControllerTest.php, src/SWP/Bundle/MenuBundle/Doctrine/ORM/MenuItemRepository.php, src/SWP/Bundle/StorageBundle/Doctrine/ORM/NestedTreeEntityRepository.php
| Fixed tickets             | SWP-1310
=> add option to change route parent and position in tree

src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php, src/SWP/Bundle/CoreBundle/spec/Enhancer/RouteEnhancerSpec.php
| Fixed tickets             | SWP-1326
=> fix loading correct template in case of route with type content

CHANGELOG.md, docs/manual/templates_system/content_list.rst, src/SWP/Bundle/ContentListBundle/Doctrine/ORM/ContentListItemRepository.php, src/SWP/Bundle/ContentListBundle/Loader/ContentListsItemLoader.php, src/SWP/Bundle/CoreBundle/Tests/Loader/ContentListItemLoaderTest.php
| Fixed tickets             | SWP-1330
=> implement excluding articles from content list item

CHANGELOG.md, features/packages/creating_package_with_authors.feature, src/SWP/Bundle/CoreBundle/EventListener/DownloadArticleAuthorAvatarListener.php, src/SWP/Bundle/CoreBundle/Manager/AuthorMediaManager.php, src/SWP/Bundle/CoreBundle/Migrations/2018/10/Version20181008115755.php, src/SWP/Bundle/CoreBundle/Model/Image.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Serializer/AuthorSerializationSubscriber.php
| Fixed tickets             | SWP-1346
=> SWP-1346 - Error in generating url to avatar image

CHANGELOG.md, src/SWP/Bundle/CoreBundle/Manager/MediaManager.php
=> Fix the assets URLs generating by Media Manager

CHANGELOG.md, docs/manual/templates_system/index.rst, docs/manual/templates_system/keywords.rst, src/SWP/Bundle/ContentBundle/Loader/KeywordLoader.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml, src/SWP/Bundle/ContentBundle/Tests/Functional/Loader/KeywordLoaderTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/app/Resources/fixtures/LoadArticlesData.php, src/SWP/Bundle/ContentBundle/Tests/Functional/app/Resources/meta/keyword.yml, src/SWP/Bundle/CoreBundle/Tests/Loader/KeywordLoaderTest.php
| Fixed tickets             | SWP-1331
=> SWP-1331 - Loader for keyword

src/SWP/Bundle/CoreBundle/Serializer/ArticlesCountHandler.php, src/SWP/Bundle/CoreBundle/Tests/Controller/TenantControllerTest.php
=> do not enable tenantable filter in articles count handler

CHANGELOG.md, src/SWP/Bundle/ContentListBundle/Loader/ContentListsItemLoader.php
| Fixed tickets             | SWP-1349
=> Do not allow empty params in ContentListsItemLoader

CHANGELOG.md, src/SWP/Bundle/ContentBundle/Resources/config/providers.orm.yml, src/SWP/Bundle/ContentBundle/Routing/Candidates/Candidates.php
| Fixed tickets             | SWP-1354
=> Exclude non-publisher created routes from RouteProvider

src/SWP/Bundle/AnalyticsBundle/Model/ContentListsAwareTrait.php, src/SWP/Bundle/CoreBundle/Model/Article.php, src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.Article.yml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Serializer/ContentListAwareSerializationSubscriber.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListItemControllerTest.php, src/SWP/Component/ContentList/Model/ListContentInterface.php
… api representation
| New feature?              | improvement
| Fixed tickets             | SWP-1364
=> [Improvement] expose content lists in article api response

app/Resources/meta/article.yml, config/packages/security.yaml, docs/manual/templates_system/articles.rst, features/02_articles/analytics.feature, features/02_articles/comments_count.feature, src/SWP/Bundle/AnalyticsBundle/Services/ArticleStatisticsService.php, src/SWP/Bundle/ContentBundle/Form/Type/ArticleCommentsType.php, src/SWP/Bundle/CoreBundle/Consumer/AnalyticsEventConsumer.php, src/SWP/Bundle/CoreBundle/Controller/ArticleCommentsController.php, src/SWP/Bundle/CoreBundle/Migrations/2018/11/Version20181106153503.php, src/SWP/Bundle/CoreBundle/Model/Article.php, src/SWP/Bundle/CoreBundle/Model/ArticleInterface.php, src/SWP/Bundle/CoreBundle/Resolver/ArticleResolver.php, src/SWP/Bundle/CoreBundle/Resolver/ArticleResolverInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Article.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.Article.yml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Resources/config/twig.yml, src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleLoaderTest.php, src/SWP/Bundle/CoreBundle/spec/Consumer/AnalyticsEventConsumerSpec.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
| Fixed tickets             | SWP-1323
=> [Feature] add option to store article comments count

config/packages/test/monolog.yaml, features/routes/management.feature, src/SWP/Bundle/CoreBundle/Context/CachedTenantContext.php, src/SWP/Bundle/CoreBundle/EventSubscriber/WebhookEventsSubscriber.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListItemControllerTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadAmpHtmlData.php
=> enable tenantable every time when new tenant is set

composer.lock, features/content_push/checking_secured_content_push.feature, src/SWP/Bundle/CoreBundle/EventListener/SecuredContentPushListener.php, src/SWP/Bundle/CoreBundle/Tests/Command/CreateTenantCommandTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/TenantControllerTest.php
=> read file content send to asset endpint correctly in secured content push

CHANGELOG.md, app/Resources/meta/author.yml, docs/manual/templates_system/article_author.rst, features/packages/creating_package_with_authors.feature, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Author.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleAuthor.orm.yml, src/SWP/Bundle/CoreBundle/Migrations/2018/11/Version20181116092734.php, src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleAuthorLoaderTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php, src/SWP/Component/Bridge/Model/Author.php, src/SWP/Component/Bridge/Model/AuthorInterface.php
| Bug fix?                  | |no
| Fixed tickets             | SWP-1376
=> Expose values for social accounts for authors

CHANGELOG.md, src/SWP/Bundle/CoreBundle/Command/ImportUserCommand.php, src/SWP/Bundle/CoreBundle/Model/User.php, src/SWP/Bundle/CoreBundle/Model/UserInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/commands.yml
| Fixed tickets             | SWP-1391
=> Added command to import users from JSON files

CHANGELOG.md, config/packages/security.yaml, config/routes/routes.yml, docs/cookbooks/templates/users_registration_and_login.rst
| Fixed tickets             | SWP-1345
=> enable password reset

composer.json, composer.lock, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php
=> allow for publishedAfter and publishedBefore in articles loader

src/SWP/Bundle/CoreBundle/EventListener/UpdatedPackageListener.php, src/SWP/Bundle/CoreBundle/Repository/ArticleRepository.php, src/SWP/Bundle/CoreBundle/Repository/ArticleRepositoryInterface.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ArticleAutoPublishTest.php, src/SWP/Bundle/CoreBundle/Tests/Functional/MultipleWebsitesPublish.php
=> use custom repository method to load package articles

app/config/parameters.yml.dist, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
=> allow to use custom vhost on rabbitmq

behat.yml, features/02_articles/comments_count.feature, features/bootstrap/FeatureContext.php, features/bootstrap/JsonContext.php, src/SWP/Bundle/ContentBundle/Doctrine/TimestampableCancelInterface.php, src/SWP/Bundle/ContentBundle/EventListener/TimestampableListener.php, src/SWP/Bundle/ContentBundle/Model/Article.php, src/SWP/Bundle/ContentBundle/Model/ArticleInterface.php, src/SWP/Bundle/ContentBundle/Resources/config/app/config.yml, src/SWP/Bundle/ContentBundle/Tests/Functional/app/ContentBundle/config.yml, src/SWP/Bundle/CoreBundle/Controller/ArticleCommentsController.php, src/SWP/Bundle/CoreBundle/Controller/StaticThemeAssetsController.php, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
=> don't change article updated time when setting new comments count value

composer.lock, features/content_push/checking_secured_content_push.feature, src/SWP/Bundle/CoreBundle/EventListener/SecuredContentPushListener.php
=> update dependencies, and disable secured token checking for assets calls

CHANGELOG.md, features/content_lists/do_not_add_articles_to_automatic_content_list.feature, src/SWP/Bundle/CoreBundle/Matcher/ArticleCriteriaMatcher.php
=> do not add articles to automatic content lists without filters set

.travis.yml, src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php, src/SWP/Bundle/CoreBundle/EventListener/RemoveItemsListener.php, src/SWP/Bundle/CoreBundle/spec/EventListener/AddArticleToListListenerSpec.php
+ add tests for php 7.3 in travis
| BC breaks?                | yes (previous behaviour was a bug)
| Fixed tickets             | SWP-1419
=> set position for new automatically added article to content list to 0 (put it at top of list)

src/SWP/Bundle/CoreBundle/Controller/AuthController.php
=> [fix] Allow to login by superdesk credentaials with user without first and last name set

features/01_webhooks/webhooks.feature, features/preview/preview_article_based_on_package_with_preview_webhook_configured.feature, src/SWP/Bundle/WebhookBundle/Form/Type/WebhookType.php, src/SWP/Bundle/WebhookBundle/Model/Webhook.php, src/SWP/Bundle/WebhookBundle/Model/WebhookInterface.php, src/SWP/Bundle/WebhookBundle/Resources/config/serializer/Model.Webhook.yml
| BC breaks?                | yes (BREAKS WEBHOOK API - we don't have any ui based on it yet)
=> work with webhooks events as an arrays in API

CHANGELOG.md, features/amp/load_amp_version_article_with_content_route.feature, src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php
| Fixed tickets             | SWP-1460
=> set slug for routes of type content to make them AMP compatible

features/content_push/send_content_with_galleries_in_associations.feature, src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleMediaListener.php, src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleSlideshowsListener.php, src/SWP/Bundle/ContentBundle/Model/ArticleMedia.php, src/SWP/Bundle/ContentBundle/Model/ArticleMediaInterface.php, src/SWP/Bundle/ContentBundle/Model/Slideshow.php, src/SWP/Bundle/ContentBundle/Model/SlideshowInterface.php, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleMedia.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Slideshow.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/SlideshowItem.orm.yml, src/SWP/Bundle/CoreBundle/Controller/SlideshowItemController.php, src/SWP/Bundle/CoreBundle/Migrations/2019/01/Version20190125102004.php, src/SWP/Component/Bridge/Model/Package.php, src/SWP/Component/Bridge/Model/PackageInterface.php
=> filter out slideshows from associations, remove old slideshows

docs/themes.rst, src/SWP/Bundle/CoreBundle/Controller/StaticThemeAssetsController.php
| Fixed tickets             | SWP-1463
=> support for ads.txt served from website root (stored in theme

scripts/supervisor/supervisor_content_push.conf
| Bug fix?                    | yes
| New feature?               |  no
| BC breaks?                 |  no
| Deprecations?              |  no
| Tests pass?                 | yes
| Changelog update required   | no
| Fixed tickets             |
| License                     | AGPLv3
=> fix overlapping process name of supervisor

src/SWP/Bundle/ContentBundle/Processor/EmbeddedMediaBlockProcessor.php
=> improve embedded media block processor

CHANGELOG.md
| Tests pass?               | yes|
=> [Release] Add missing features/fixes to changelog for 1.5

CHANGELOG.md, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Package.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Rendition.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleMedia.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleSource.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Slideshow.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/SlideshowItem.orm.yml, src/SWP/Bundle/ContentListBundle/Resources/config/doctrine-orm/ContentList.orm.yml, src/SWP/Bundle/ContentListBundle/Resources/config/doctrine-orm/ContentListItem.orm.yml, src/SWP/Bundle/MultiTenancyBundle/Resources/config/doctrine-orm/Organization.orm.yml, src/SWP/Bundle/MultiTenancyBundle/Resources/config/doctrine-orm/Tenant.orm.yml
=> turn off loggable extensions on tables

src/SWP/Bridge/JMSSerializerBundle/composer.json, src/SWP/Bundle/AnalyticsBundle/composer.json, src/SWP/Bundle/BridgeBundle/composer.json, src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/ContentListBundle/composer.json, src/SWP/Bundle/CoreBundle/composer.json, src/SWP/Bundle/ElasticSearchBundle/composer.json, src/SWP/Bundle/FixturesBundle/composer.json, src/SWP/Bundle/MenuBundle/composer.json, src/SWP/Bundle/MultiTenancyBundle/composer.json, src/SWP/Bundle/OutputChannelBundle/composer.json, src/SWP/Bundle/PaywallBundle/composer.json, src/SWP/Bundle/RuleBundle/composer.json, src/SWP/Bundle/SettingsBundle/composer.json, src/SWP/Bundle/StorageBundle/composer.json, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Bundle/UserBundle/composer.json, src/SWP/Bundle/WebhookBundle/composer.json, src/SWP/Component/Bridge/composer.json, src/SWP/Component/Common/composer.json, src/SWP/Component/ContentList/composer.json, src/SWP/Component/MultiTenancy/composer.json, src/SWP/Component/OutputChannel/composer.json, src/SWP/Component/Paywall/composer.json, src/SWP/Component/Revision/composer.json, src/SWP/Component/Rule/composer.json, src/SWP/Component/Storage/composer.json, src/SWP/Component/TemplatesSystem/composer.json, src/SWP/Component/Webhook/composer.json
=> bump bundles and libraries dev version

app/config/config_dev.yml, composer.json, composer.lock, config/packages/framework.yaml, src/SWP/Bundle/AnalyticsBundle/EventListener/AnalyticsEventListener.php, src/SWP/Bundle/CoreBundle/Theme/Model/Theme.php
Downgrade knp/time-ago, serialize all theme fields, don't count OPTIONS requests as pageviews, re-enable translations page in dev
=> [fixes] Theme Locale Fixes

src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Loader/ArticleLoaderTest.php, src/SWP/Bundle/ContentBundle/Tests/Functional/app/Resources/fixtures/LoadArticlesData.php, src/SWP/Component/Bridge/Model/BaseContent.php, src/SWP/Component/Bridge/spec/Model/BaseContentSpec.php
=> [improvement] allow to filter articles by data stored in extra

CHANGELOG.md, features/02_articles/set_width_and_height_of_embedded_image.feature, features/settings/listing_settings.feature, features/settings/restoring_settings_by_scope.feature, features/settings/updating_multiple_settings_at_once.feature, src/SWP/Bundle/ContentBundle/Processor/EmbeddedImageProcessor.php, src/SWP/Bundle/ContentBundle/Processor/EmbeddedImageProcessorInterface.php, src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.ArticleMedia.yml, src/SWP/Bundle/ContentBundle/Tests/Functional/EventListener/ProcessArticleMediaListenerTest.php, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideEmbeddedImageProcessorPass.php, src/SWP/Bundle/CoreBundle/Processor/EmbeddedImageProcessor.php, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
| Fixed tickets             | SWP-1501
=> Set image byline/credit metadata field in the HTML output

src/SWP/Component/Bridge/Model/BaseContent.php, src/SWP/Component/Bridge/Model/ContentInterface.php
| Fixed tickets             | SWP-1503
=> allow to define publishing rules based on subjects shemes and names

src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php
This will allow to filter articles having some extra set (without providing value) and exclude them. 
ex: `with { "extra": { "videoemb": "***" } }`
=> allow to exclude by extra, improve filtering

app/Resources/meta/article.yml, src/SWP/Bundle/AnalyticsBundle/Model/ContentListsAwareTrait.php, src/SWP/Bundle/ContentListBundle/composer.json, src/SWP/Bundle/CoreBundle/EventSubscriber/Meta/ArticleContentListsSubscriber.php, src/SWP/Bundle/CoreBundle/Model/PublishDestination.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Serializer/ArticlesCountHandler.php, src/SWP/Bundle/CoreBundle/Tests/Controller/RuleControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Functional/DynamicArticleContentListsLoadingInMetaTest.php, src/SWP/Bundle/CoreBundle/Tests/Routing/MetaRouterTest.php, src/SWP/Bundle/TemplatesSystemBundle/Resources/config/services.yml, src/SWP/Component/TemplatesSystem/Gimme/Context/Context.php, src/SWP/Component/TemplatesSystem/Gimme/Event/MetaEvent.php, src/SWP/Component/TemplatesSystem/Gimme/Meta/Meta.php, src/SWP/Component/TemplatesSystem/Tests/Gimme/Context/ContextTest.php, src/SWP/Component/TemplatesSystem/Tests/Gimme/Loader/ArticleLoaderTest.php, src/SWP/Component/TemplatesSystem/Tests/Gimme/Loader/ChainLoaderTest.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Extension/GimmeExtensionTest.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/GimmeListNodeTest.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/GimmeNodeTest.php, src/SWP/Component/TemplatesSystem/composer.json, src/SWP/Component/TemplatesSystem/spec/Gimme/Context/ContextSpec.php
| Fixed tickets             | SWP-1471
=> implement simple events support in meta class, implement dynamic loading of article content lists

src/SWP/Bundle/UserBundle/DependencyInjection/Compiler/DisableLastLoginListenerPass.php, src/SWP/Bundle/UserBundle/SWPUserBundle.php
=> don't log user login (with user updated at change)

docker/php7-fpm/Dockerfile
| New feature?              |no
| BC breaks?                |no
| Fixed tickets             | #741
=> Added missing sockets module from php Dockerfile

src/SWP/Bundle/CoreBundle/Model/Article.php, src/SWP/Bundle/CoreBundle/Model/ArticleInterface.php, src/SWP/Bundle/CoreBundle/Model/Package.php, src/SWP/Bundle/CoreBundle/Service/ArticlePublisher.php
| Fixed tickets             | SWP-1369
=> add article to package on publish

features/rules/adding_article_to_bucket_based_on_rules.feature, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php, src/SWP/Bundle/ContentListBundle/Doctrine/ORM/ContentListItemRepository.php, src/SWP/Bundle/CoreBundle/Controller/RedirectingController.php, src/SWP/Bundle/CoreBundle/Model/ContentList.php, src/SWP/Bundle/CoreBundle/Model/ContentListItemsCountInterface.php, src/SWP/Bundle/CoreBundle/Model/ContentListItemsCountTrait.php, src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.ContentList.yml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Serializer/ContentListItemsCountHandler.php, src/SWP/Component/ContentList/Repository/ContentListItemRepositoryInterface.php
| Fixed tickets             | SWP-1507
=> show content list items count on content list object in api

app/config/config_test.yml, app/config/parameters.yml.dist, features/content_push/checking_if_tenant_rules_are_not_evaluated.feature, features/packages/add_random_chars_to_slug_ending_with_a_number.feature, features/packages/assigning_existing_author_to_another_package.feature, features/packages/send_package_with_this_same_slug_twice.feature, features/preview/preview_article_based_on_package_data.feature, features/preview/preview_article_based_on_package_when_route_template_is_not_set.feature, features/preview/preview_article_based_on_package_with_single_slideshow.feature, features/preview/preview_article_based_on_package_with_slideshows.feature, features/preview/preview_article_slideshow_with_video_audio_image.feature, features/preview/preview_article_when_fake_template_is_set.feature, features/preview/preview_article_with_embedded_and_featured_media.feature, features/preview/preview_single_slideshows.feature, src/SWP/Behat/Service/RandomStringGeneratorStub.php, src/SWP/Bundle/CoreBundle/EventListener/DuplicatedSlugListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/Functional/ArticleSourcesTest.php, src/SWP/Component/Common/Generator/GeneratorInterface.php, src/SWP/Component/Common/Generator/RandomStringGenerator.php, src/SWP/Component/Common/spec/Generator/RandomStringGeneratorSpec.php
| Fixed tickets             | SWP-1516
=> allow to add random string to end of a slug when it's matching configured regex

app/config/parameters.yml.dist, src/SWP/Bundle/ElasticSearchBundle/Controller/Api/ArticleSearchController.php, src/SWP/Bundle/ElasticSearchBundle/Loader/SearchResultLoader.php, src/SWP/Bundle/ElasticSearchBundle/Repository/ArticleRepository.php, src/SWP/Bundle/ElasticSearchBundle/Repository/PackageRepository.php, src/SWP/Bundle/ElasticSearchBundle/Resources/config/app/config.yml, src/SWP/Bundle/ElasticSearchBundle/Resources/config/loader.yml
| Bug fix?                  | |no
| Fixed tickets             | SWP-1502
=> optimize elasticsearch multimatch query

src/SWP/Bundle/ContentBundle/Processor/EmbeddedVideoProcessor.php
=> do not replace video src when file does not exist

src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php
| Fixed tickets             | swp-1524
=> stop consumer process when there is problem with database connection

src/SWP/Bundle/CoreBundle/Migrations/2019/03/Version20190312113241.php, src/SWP/Bundle/CoreBundle/Model/Article.php, src/SWP/Bundle/CoreBundle/Repository/ArticleRepository.php
=> don't keep null's in article comments_count

features/packages/get_related_items_by_package.feature, src/SWP/Bundle/CoreBundle/Controller/RelatedArticleOrganizationController.php
| Fixed tickets             | SWP-1555
=> get related articles by package id - API

features/targeted_publishing/creating_targeted_publishing_destinations_with_content_lists.feature, src/SWP/Bundle/CoreBundle/Processor/ArticleMediaProcessor.php
=> fix preview with text items (related articles) in item associations

CHANGELOG.md, app/Resources/meta/media.yml, behat.yml, config/packages/test/behat.yaml, features/content_push/send_content_with_feature_media.feature, features/content_push/send_content_with_galleries_in_associations.feature, src/SWP/Behat/Contexts/PackageContext.php, src/SWP/Behat/Contexts/UserContext.php, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Item.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.BaseContent.yml, src/SWP/Bundle/ContentBundle/Model/ArticleMedia.php, src/SWP/Bundle/ContentBundle/Model/ArticleMediaInterface.php, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleMedia.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.ArticleMedia.yml, src/SWP/Bundle/CoreBundle/EventListener/TenantRevisionListener.php, src/SWP/Bundle/CoreBundle/Migrations/2019/03/Version20190320132523.php, src/SWP/Bundle/CoreBundle/Migrations/2019/03/Version20190320142338.php, src/SWP/Component/Bridge/Model/BaseContent.php, src/SWP/Component/Bridge/Model/ContentInterface.php
| Fixed tickets             | SWP-1554
=> expose more metadata in article media

features/content_push/check_article_body_via_webhook.feature, src/SWP/Behat/Contexts/WebhookContext.php, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php, src/SWP/Bundle/ContentBundle/Model/Article.php, src/SWP/Bundle/ContentListBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Consumer/AnalyticsEventConsumer.php, src/SWP/Bundle/TemplatesSystemBundle/DataCollector/ContextDataCollector.php, src/SWP/Bundle/TemplatesSystemBundle/DataCollector/MetaLoaderCollector.php, src/SWP/Bundle/TemplatesSystemBundle/DependencyInjection/SWPTemplatesSystemExtension.php, src/SWP/Bundle/TemplatesSystemBundle/Loader/TraceableChainLoader.php, src/SWP/Bundle/TemplatesSystemBundle/Resources/config/services.yml, src/SWP/Bundle/TemplatesSystemBundle/Resources/config/services_dev.yml, src/SWP/Bundle/TemplatesSystemBundle/Resources/views/Collector/contextCollector.html.twig, src/SWP/Bundle/TemplatesSystemBundle/Resources/views/Collector/loadersCollector.html.twig, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Component/MultiTenancy/Resolver/TenantResolver.php, src/SWP/Component/TemplatesSystem/Gimme/Loader/MemoryCachedLoader.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Loader/ChainLoaderSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Loader/MemoryCachedLoaderSpec.php
=> add memory cached loader - use it for content list loader, remove www cleaning from host

features/content_push/send_content_with_galleries_in_associations.feature, src/SWP/Behat/Contexts/WebhookContext.php, src/SWP/Bundle/ContentBundle/Tests/Functional/EventListener/ProcessArticleMediaListenerTest.php, src/SWP/Bundle/ContentListBundle/Resources/config/services.yml, src/SWP/Bundle/TemplatesSystemBundle/Resources/views/Collector/contextCollector.html.twig, src/SWP/Component/MultiTenancy/spec/Resolver/TenantResolverSpec.php
| Bug fix?                  | ye
=> fix spec tests for www subdomain, improve some collector views

src/SWP/Bundle/ContentBundle/Controller/MediaController.php, src/SWP/Bundle/CoreBundle/Context/CachedTenantContext.php, src/SWP/Bundle/CoreBundle/EventListener/TenantRevisionListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/MultiTenancyBundle/Doctrine/ORM/TenantRepository.php, src/SWP/Component/MultiTenancy/Resolver/TenantResolver.php
Don't cache whole request (with file inside) cache only database call in media controller, don't fetch revisions on media requests
=> [1.5] Media fixes

src/SWP/Bundle/ContentBundle/Controller/MediaController.php, src/SWP/Bundle/CoreBundle/Context/CachedTenantContext.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/ElasticSearchBundle/Repository/ArticleRepository.php, src/SWP/Bundle/MultiTenancyBundle/Doctrine/ORM/TenantRepository.php, src/SWP/Component/MultiTenancy/Resolver/TenantResolver.php
=> Merge 1.5 to master

CHANGELOG.md, src/SWP/Bundle/CoreBundle/Command/ProcessArticleBodyCommand.php, src/SWP/Bundle/ElasticSearchBundle/Loader/SearchResultLoader.php, src/SWP/Bundle/ElasticSearchBundle/Repository/ArticleRepository.php
| Fixed tickets             | SWP-1591
=> fixed search pagination & make search by body optional

composer.json, composer.lock, src/SWP/Behat/Contexts/RuleContext.php, src/SWP/Bundle/ContentBundle/Loader/PaginatedLoader.php, src/SWP/Bundle/CoreBundle/Repository/ApiKeyRepository.php, src/SWP/Bundle/CoreBundle/Security/Authenticator/TokenAuthenticator.php, src/SWP/Bundle/MultiTenancyBundle/Tests/Command/CreateOrganizationCommandTest.php, src/SWP/Bundle/MultiTenancyBundle/Tests/Command/CreateTenantCommandTest.php, src/SWP/Bundle/RuleBundle/Form/Type/RuleType.php, src/SWP/Bundle/RuleBundle/spec/Form/Type/RuleTypeSpec.php, src/SWP/Bundle/StorageBundle/Doctrine/ORM/EntityRepositoryTrait.php, src/SWP/Bundle/StorageBundle/Form/Type/UnstructuredType.php, src/SWP/Bundle/TemplatesSystemBundle/Form/Type/WidgetType.php
=> fix pagination and authetication classes

PULL_REQUEST_TEMPLATE.md
=> add new pull request template

composer.json, composer.lock
=> move dotenv to required

src/SWP/Bundle/CoreBundle/Theme/Translation/ThemeAwareTranslator.php
=> use correct interface

src/SWP/Bundle/CoreBundle/Theme/Translation/ThemeAwareTranslator.php
=> keep legacy interface (for knp paginator bundle)

composer.lock, features/content_push/update_article_keywords.feature, src/SWP/Bundle/ContentBundle/Hydrator/ArticleHydrator.php, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/GimmeListNodeTest.php
=> clear keywords on article update

composer.json, composer.lock, src/SWP/Component/TemplatesSystem/Tests/Twig/Node/GimmeListNodeTest.php, symfony.lock
=> add weblink component - it will allow to prefetch resources from themes

features/02_articles/unpublish_article_when_killed.feature, features/02_articles/unpublish_corrected_article_when_killed.feature, src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php
=> kill article when it's corrected

config/packages/test/behat.yaml, features/routes/delete_route_references.feature, src/SWP/Behat/EventSubscriber/SQLiteForeignKeyEnabler.php, src/SWP/Bundle/CoreBundle/Migrations/2019/05/Version20190510102330.php, src/SWP/Bundle/CoreBundle/Migrations/2019/05/Version20190510112541.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/PackagePreviewToken.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/PublishDestination.orm.yml
=> Delete route and resources referencing it

src/SWP/Bundle/ElasticSearchBundle/Repository/ArticleRepository.php, src/SWP/Bundle/ElasticSearchBundle/Repository/PackageRepository.php
=> Search improvements

features/packages/editing_seo_metadata.feature, src/SWP/Bundle/CoreBundle/Controller/SeoMetadataController.php
=> added api endpoint to get seo metadata for package

src/SWP/Bundle/CoreBundle/Controller/RedirectingController.php, src/SWP/Bundle/CoreBundle/Repository/ArticleRepository.php, src/SWP/Bundle/CoreBundle/Repository/ArticleRepositoryInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/controllers.yaml, src/SWP/Bundle/CoreBundle/Tests/Controller/RedirectingControllerTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php, src/SWP/Component/Common/Criteria/Criteria.php
=> Look for article based on his extra data value in redirection controller

features/content_push/send_content_with_related_items.feature, features/packages/get_related_items_by_package.feature, src/SWP/Bundle/ContentBundle/EventListener/ProcessRelatedArticlesListener.php, src/SWP/Bundle/CoreBundle/Controller/RelatedArticleOrganizationController.php
=> Related articles improvements

features/02_articles/unpublish_killed_when_publish_destination_is_defined.feature, src/SWP/Bundle/CoreBundle/EventListener/CanceledPackageListener.php
=> fixed: Killed article is still available on the website

features/commands/process_packages_command.feature, src/SWP/Bundle/CoreBundle/Command/ProcessPackagesCommand.php, src/SWP/Bundle/CoreBundle/Repository/PackageRepository.php, src/SWP/Bundle/CoreBundle/Repository/PackageRepositoryInterface.php
=> add filtering by article body and lead search term in package process command

composer.json, composer.lock, features/amp/ignore_invalid_tags_on_amp_convert.feature, src/SWP/Bundle/ContentBundle/Model/Article.php, src/SWP/Bundle/CoreBundle/Controller/AmpController.php, src/SWP/Bundle/CoreBundle/DependencyInjection/SWPCoreExtension.php, src/SWP/Bundle/CoreBundle/Resources/config/controllers.yaml
Fixed tickets : SWP-1640
Also
- ported AMP controller caching from the master branch
=> Ignore invalid embed tags when converting to AMP

composer.json, composer.lock, src/SWP/Bundle/CoreBundle/Translation/MessageFormatter.php
=> Fixed ago filter and it's pluralization

src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleMediaListener.php
=> don't re-fetch related articles images

features/redirecting/redirecting_with_unpublished_article.feature, src/SWP/Bundle/CoreBundle/Controller/RedirectingController.php, src/SWP/Bundle/CoreBundle/Repository/ArticleRepository.php
=> [Fix] Redirecting to unpublished

features/content_push/duplicated_article_handling.feature, src/SWP/Bundle/CoreBundle/Migrations/2019/07/Version20190709090034.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Article.orm.yml
=> fix invalid uinique contraint on article slug

composer.lock, features/content_push/duplicated_article_handling.feature, src/SWP/Bundle/CoreBundle/Migrations/2019/07/Version20190709090034.php, src/SWP/Bundle/CoreBundle/Resolver/ArticleResolver.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Article.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Tests/ContentPushTest.php
=> [Merge] 1.5 to master

.travis.yml, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Package.orm.yml, src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php, src/SWP/Bundle/CoreBundle/EventListener/TenantRevisionListener.php, src/SWP/Bundle/CoreBundle/Migrations/2019/07/Version20190710074938.php, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml
=> Make guid unique in package table, lock package processing in content push

composer.json, composer.lock, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Package.orm.yml, src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php, src/SWP/Bundle/CoreBundle/Migrations/2019/07/Version20190710074938.php, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Resources/config/consumers.yml, symfony.lock
=> make guid unique in package, lock package processing in content push

features/content_push/send_content_with_related_items.feature, src/SWP/Bundle/ContentBundle/EventListener/ProcessRelatedArticlesListener.php, src/SWP/Bundle/ContentBundle/Loader/RelatedArticleLoader.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Loader/RelatedArticleLoaderTest.php
=> order related articles by id desc by default

composer.json, composer.lock
=> update dependencies, use fixed stringify package

src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentListBundle/Form/Type/ContentListType.php, src/SWP/Bundle/CoreBundle/Consumer/ImageConversionConsumer.php, src/SWP/Bundle/CoreBundle/Controller/AuthController.php, src/SWP/Bundle/CoreBundle/Resources/config/controllers.yaml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Version/Version.php
=> refactor auth controller to new Symfony way, log issues with superdesk authentication

features/content_push/validating_to_long_byline.feature, src/SWP/Component/Bridge/Validator/NinjsValidator.php
=> validate content length with json schema

src/SWP/Bundle/ContentBundle/EventListener/MimeTypeListener.php, src/SWP/Bundle/ContentBundle/Tests/EventListener/MimeTypeListenerTest.php
=> Read content type from route

.env.test, config/packages/security.yaml, features/user/user_settings.feature, src/SWP/Bundle/CoreBundle/Controller/ArticleCommentsController.php, src/SWP/Bundle/CoreBundle/Controller/CurrentThemeController.php, src/SWP/Bundle/UserBundle/Controller/UserController.php, src/SWP/Bundle/UserBundle/DependencyInjection/SWPUserExtension.php, src/SWP/Bundle/UserBundle/Resources/config/controllers.yml, src/SWP/Bundle/UserBundle/Resources/config/services.yml
=> add endpoints for user settings get and update

src/SWP/Bundle/ContentListBundle/Form/Type/ContentListType.php, src/SWP/Bundle/ContentListBundle/spec/Form/Type/ContentListTypeSpec.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Serializer/ContentListSerializationSubscriber.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListItemControllerTest.php, src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/test/list_content.yml
=> use snake_case ion form and and api response, but in database keep camels case for criteria matching

src/SWP/Bundle/ContentListBundle/Form/Type/ContentListType.php, src/SWP/Bundle/CoreBundle/Resources/config/output_channel_adapter.yml, src/SWP/Bundle/CoreBundle/Tests/Functional/Resources/server.js, src/SWP/Component/Paywall/Adapter/PaymentsHubAdapter.php
=> use v1 api version of paymenthub in adapter

CHANGELOG.md
=> add ouath to changelog

bin/UpdateApplicationVersion.php, src/SWP/Bundle/CoreBundle/Version/Version.php
=> bump versions to rc

CHANGELOG.md, UPGRADE.md, docs/cookbooks/implementators/index.rst, docs/cookbooks/implementators/setup_oauth_login_with_auth0.rst, docs/reference/system_requirements.rst, src/SWP/Bundle/ContentBundle/composer.json
=> add more upgrade notes

features/content_lists/add_article_to_multiple_automatic_content_lists.feature, src/SWP/Behat/Contexts/ContentListContext.php, src/SWP/Behat/Contexts/RouteContext.php, src/SWP/Bundle/ContentBundle/Rule/Applicator/ArticleRuleApplicator.php, src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php, src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php, src/SWP/Bundle/CoreBundle/Matcher/ArticleCriteriaMatcher.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Rule/Populator/ArticlePopulator.php, src/SWP/Bundle/CoreBundle/Service/ArticlePublisher.php
=> fix articles catching for automated content lists

config/routes.yaml, src/SWP/Bundle/ContentBundle/DependencyInjection/Compiler/OverrideCmfFinalMatcherPass.php, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/ContentBundle/Routing/FinalMatcher.php, src/SWP/Bundle/ContentBundle/SWPContentBundle.php, src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php, src/SWP/Bundle/CoreBundle/Tests/Controller/RedirectingControllerTest.php
=> handle url's with trailing slashes properly

features/02_articles/alt_text_for_embedded_images.feature, src/SWP/Bundle/ContentBundle/Processor/EmbeddedImageProcessor.php, src/SWP/Bundle/CoreBundle/Processor/EmbeddedImageProcessor.php
=> VIJ-170 - set fallback alt text value for embedded images

src/SWP/Bundle/CoreBundle/Resources/config/services.yml
=> SWP-1730 - Themes are not loaded in the website settings

src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php
=> handle package correction for update without original package in publisher

src/SWP/Bundle/CoreBundle/Theme/Model/Theme.php
=> Uploaded logo is visible in theme customization only after revisiting

README.md, src/SWP/Bundle/CoreBundle/Command/FixIncompleteImagesDataCommand.php, src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideAssetLocationResolver.php, src/SWP/Bundle/CoreBundle/Resources/config/commands.yml
Fixes SWP-1684
- add new command for migration fixes
- fix edge case reported by client connected to corrections
=> Fix wrong renditions sizes, fix article corrections case

src/SWP/Bundle/CoreBundle/Model/ContentList.php, src/SWP/Bundle/CoreBundle/Model/ContentListInterface.php, src/SWP/Bundle/CoreBundle/Repository/ContentListItemRepository.php, src/SWP/Bundle/CoreBundle/Repository/ContentListItemRepositoryInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.ContentList.yml, src/SWP/Bundle/CoreBundle/Serializer/ContentListSerializationSubscriber.php, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListControllerTest.php
- don't returns whole article (with images, slideshows etc when serialized in latest content list items)
=> use custom query for fetching latest content list items - return only id and title

features/content_push/send_content_with_galleries_and_related_content.feature, src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleSlideshowsListener.php, src/SWP/Bundle/CoreBundle/Processor/ArticleMediaProcessor.php
- correctly filter out related content before slideshows handling
=> don't treat related articles as slideshows

composer.lock
=> updated amp library containing amp-sticky-ad fix

features/packages/publish_package_with_tenant_rules.feature, src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php
- Flush remaining changes (after listeners work) after content push (creation)
=> fix package status after publication (flush left package changes)

features/packages/publish_package_with_tenant_rules.feature, src/SWP/Bundle/ContentBundle/Service/ArticleService.php, src/SWP/Bundle/ContentBundle/Service/ArticleServiceInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Service/ArticlePublisher.php
- Fire POST_PUBLISHED after article publication
=> fire post published event in article publisher

src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Item.orm.yml, src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php
=> manually persist groups and fixed relationship mapping between group and items

src/SWP/Bundle/CoreBundle/DependencyInjection/SWPCoreExtension.php
=> add namespace to main cache - so every deployment will have his own cache version

composer.lock, features/content_push/send_content_with_related_items.feature, src/SWP/Bundle/ContentBundle/EventListener/ProcessRelatedArticlesListener.php, src/SWP/Bundle/ContentBundle/Loader/RelatedArticleLoader.php, src/SWP/Bundle/ContentBundle/Tests/Functional/Loader/RelatedArticleLoaderTest.php
=> 1.5 to 2.0 merge

features/02_articles/articles_sorting.feature, src/SWP/Bundle/ElasticSearchBundle/Controller/Api/ArticleSearchController.php, src/SWP/Bundle/ElasticSearchBundle/Resources/config/app/config.yml
This will require to repopulate the ES index
Fixes SWP-1358
=> allow to sort articles by page views in elastic search

src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php
=> remove existing package's groups on package update

src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.Article.yml, src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php
=> add missing article properties

bin/UpdateApplicationVersion.php, composer.json, composer.lock, config/packages/sentry.yaml, src/SWP/Bundle/ContentBundle/DependencyInjection/Compiler/RegisterMediaFactoryPass.php, src/SWP/Bundle/ContentBundle/Factory/ORM/MediaFactory.php, src/SWP/Bundle/ContentBundle/Resources/config/app/config.yml, src/SWP/Bundle/ContentBundle/Tests/Functional/app/ContentBundle/bundles.php, src/SWP/Bundle/ContentBundle/Tests/Functional/app/ContentBundle/config.yml, src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideMediaFactoryPass.php, symfony.lock
- log catched and handled errors to sentry
=> log errors from content push consumer and media download to sentry

src/SWP/Bundle/WebhookBundle/AUTHORS.md, src/SWP/Bundle/WebhookBundle/LICENSE.md, src/SWP/Bundle/WebhookBundle/README.md, src/SWP/Component/Webhook/AUTHORS.md, src/SWP/Component/Webhook/LICENSE.md, src/SWP/Component/Webhook/README.md
=> Missing meta files

etc/scripts/varnish/default.vcl, public/index.php, src/SWP/Behat/Contexts/ArticleContext.php, src/SWP/Bundle/CoreBundle/EventSubscriber/HttpCacheSubscriber.php
- fix tags array composition
- update default varnish config
- always disable debug when env is prod
=> fix tags array composition, update default varnish config, always disable debug when env is prod

src/SWP/Bundle/ContentBundle/EventListener/ArticlePublishListener.php, src/SWP/Bundle/ContentBundle/spec/EventListener/ArticlePublishListenerSpec.php
Fixes #
there are two versions for updating a published article.
1) only some grammar corrections --> no republishing/ every timestamp stays the same (modified date will not be updated) no changes for date!
2) content adjustments or changes --> republishing / time stamp for modified date changes because of the new content inside the article --> also in FE there should be the modified date displayed
=> [FEATURE] modified date when updating a published article

app/Resources/meta/article.yml, features/content_lists/add_article_to_multiple_automatic_content_lists.feature, src/SWP/Bundle/ContentBundle/Model/Article.php, src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleLoaderTest.php, src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
Fixes #SWP-1667
- add option to get first places deifined in article metadata with simple short syntax article.place.city
=> expose article place

src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleAuthor.orm.yml, src/SWP/Bundle/CoreBundle/Migrations/2019/11/Version20191113081727.php, src/SWP/Component/Bridge/Model/Author.php
Fixes # SWP-1667
- add missing migration for removing article_events table
- add new image field - length
=> change author biography from string to text in database

src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php
fix searchin for articles with array in filters metadata property (ex place or subject)
=> Fix content list filling when criteria have complex subject or place

features/packages/creating_package_with_authors.feature, src/SWP/Bundle/ContentBundle/EventListener/UpdatePackageAuthorsListener.php
Fixes #SWP-1812 
- In `UpdatePackageAuthorsListener` add author to package only once
=> [SWP-1812] handle duplicated authors in package

docs/manual/templates_system/search.rst, features/02_articles/searching_articles_by_keywords.feature, src/SWP/Bundle/ElasticSearchBundle/Controller/Api/ArticleSearchController.php, src/SWP/Bundle/ElasticSearchBundle/Repository/ArticleRepository.php
- added possibility to filter articles by keywords in templates
- added possibility to filter articles by keywords in API
=> Filter articles by keywords

composer.lock, features/paywall/marking_article_as_paywall_secured_by_rule.feature, src/SWP/Bundle/ContentBundle/Rule/Applicator/ArticleRuleApplicator.php, src/SWP/Bundle/CoreBundle/Rule/Applicator/PackageRuleApplicator.php, src/SWP/Bundle/CoreBundle/Rule/Applicator/PaywallSecuredRuleApplicator.php, src/SWP/Bundle/CoreBundle/Rule/Applicator/PublishArticleToFBIARuleApplicator.php, src/SWP/Bundle/MultiTenancyBundle/Tests/DependencyInjection/Compiler/ConfigurePrefixCandidatesCompilerPassTest.php
Configuration Resolver in applicators did not allowed extra options and was rejecting applicator when single rule contained two options from another applicator
Fixes: Articles landing in incomming stage of publisher even when autopublish rule exists.  
=> fix article publishing when tenant rule contains autopublishing and paywall settings

src/SWP/Bundle/ContentBundle/Model/ArticleMediaInterface.php
=> Extend ArticleMediaInterface by TimestampableInterface

.gitignore, composer.json, composer.lock, src/SWP/Bundle/ContentBundle/EventListener/PopulateArticleAuthorSlugListener.php, src/SWP/Bundle/ContentBundle/Model/ArticleMediaInterface.php, src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php, src/SWP/Bundle/CoreBundle/Model/Package.php, src/SWP/Bundle/CoreBundle/Twig/Cache/KeyGenerator/TenantAwareMetaKeyGenerator.php, src/SWP/Bundle/CoreBundle/Twig/Cache/Strategy/LifetimeCacheStrategy.php, src/SWP/Bundle/CoreBundle/Twig/Cache/Strategy/TagAwareIndexedChainingCacheStrategy.php
Fixed for issues found after client deployment
=> downgrade doctrine-extensions, manually set created_at, fix cache keygeneration

composer.json, composer.lock
reload parent classes metadata when missing in cache
=> use fixed gedmo version

composer.json, composer.lock, src/SWP/Bundle/ContentBundle/Manager/MediaManager.php
As content push is async then there can be a situation when other instance will save that file in between of file exist check and actual saving
- Handle exception `FileExistsException`
=> Handle case when multiple instances work with this same storage

features/bootstrap/FeatureContext.php, features/bootstrap/JsonContext.php, features/targeted_publishing/content_lists/creating_targeted_publishing_destinations_with_content_lists.feature, src/SWP/Bundle/ContentListBundle/Services/ContentListService.php, src/SWP/Component/ContentList/Model/ContentListItem.php
Fixes case when article is not visible on list after publishing
- Handle case when new item is added via targeted publishing, set new value to updated_at field for content list in this case
=> update content list when new item is added to it

src/SWP/Bundle/ContentBundle/Resolver/AssetLocationResolver.php, src/SWP/Bundle/ContentBundle/spec/Resolver/AssetLocationResolverSpec.php
- correctly add slash after prefix if it is set in case of aws storage
=> fix asset location resolver logic

features/content_lists/add_article_to_multiple_automatic_content_lists.feature, src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php, src/SWP/Component/Common/Model/SoftDeletableInterface.php, src/SWP/Component/Common/Model/SoftDeletableTrait.php
Makes sures that SWP-1841 is not valid
- add new mothod for easier restoring softdeleted entities
=> add tests for article unpublishing and removing items from content list

.github/workflows/rebase.yml
GitHub action to automatically rebase PRs https://github.com/marketplace/actions/automatic-rebase
=> Create rebase action

composer.lock, src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleMediaListener.php, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Image.orm.yml, src/SWP/Bundle/ContentBundle/Tests/Functional/app/ContentBundle/config.yml, src/SWP/Bundle/CoreBundle/Migrations/2020/01/Version20200109113028.php, symfony.lock
Fixes slow article processing with galery and multiple images (gallery with ~40 items took over 2 minutes, with this index it takes around 15 seconds). 
- add index for asset_id in swp_image
=> fix content push performance with many galery items

src/SWP/Bundle/CoreBundle/Controller/ContentListController.php, src/SWP/Bundle/CoreBundle/EventListener/RemoveItemsListener.php
Fixes #
Content list items are not refreshed when the content list limit is changed.
When the limit of the content list is changed, the items behind the set limit will be removed from the list.
=> update content list items based on list limit

src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Route.orm.yml, src/SWP/Bundle/ContentListBundle/Services/ContentListService.php
=> fix limiting content list items when limtit is bigger than 10

src/SWP/Bundle/GeoIPBundle/Resources/config/services.yaml
=> lazy load GEIP checker - so it's not loaded on every request

features/content_lists/change_limit_of_content_lists.feature, src/SWP/Bundle/CoreBundle/EventListener/UpdateContentListItemsListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml
=> fix reseting manual content list items whhen list limit changed

composer.lock, features/content_lists/change_limit_of_content_lists.feature, features/twig/cache_key_generation.feature, features/twig/cache_tags_collector.feature, src/SWP/Bundle/CoreBundle/EventListener/BodyListener.php, src/SWP/Bundle/CoreBundle/EventListener/UpdateContentListItemsListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Twig/Cache/Strategy/TagAwareIndexedChainingCacheStrategy.php
=> Merge 2.0 to master

src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Author.yml, src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.Article.yml, src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php, src/SWP/Bundle/ElasticSearchBundle/Controller/Api/ArticleSearchController.php, src/SWP/Bundle/ElasticSearchBundle/Controller/Api/PackageSearchController.php
- expose article authors in packages, articles and content list items endpoints responses
=> add article authors to packages, articles and content list items responses

features/analytics/export_article_analytics.feature, src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalytics.php, src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalyticsHandler.php, src/SWP/Bundle/CoreBundle/Controller/AnalyticsExportController.php, src/SWP/Bundle/CoreBundle/Form/Type/ExportAnalyticsRouteType.php, src/SWP/Bundle/CoreBundle/Form/Type/ExportAnalyticsType.php, src/SWP/Bundle/CoreBundle/Migrations/2020/02/Version20200206100212.php
=> Analytics Export improvements

features/twig/loaders/exclude_articles_by_authors.feature, src/SWP/Behat/Contexts/ArticleContext.php, src/SWP/Behat/Contexts/TemplatingContext.php, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.BaseContent.yml, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php, src/SWP/Bundle/ContentBundle/Model/ArticleAuthorReference.php, src/SWP/Bundle/ContentBundle/Provider/ORM/ArticleProvider.php, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Article.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleAuthorReference.orm.yml
=> improve articles excluding bu authors

behat.yml.dist, config/packages/messenger.yaml, config/packages/test/behat.yaml, config/packages/test/messenger.yaml, features/failure_queue/list_items_from_failure_queue.feature, src/SWP/Behat/Contexts/MessengerContext.php, src/SWP/Behat/Service/FailedEntriesProvider.php, src/SWP/Behat/Stamp/RedeliveryStamp.php, src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalytics.php, src/SWP/Bundle/CoreBundle/Controller/FailedQueueController.php, src/SWP/Bundle/CoreBundle/MessageHandler/Message/ContentPushMessage.php, src/SWP/Bundle/CoreBundle/MessageHandler/Message/ContentPushMigrationMessage.php, src/SWP/Bundle/CoreBundle/MessageHandler/Message/ConvertImageMessage.php, src/SWP/Bundle/CoreBundle/MessageHandler/Message/MessageInterface.php, src/SWP/Bundle/CoreBundle/Model/FailedEntry.php, src/SWP/Bundle/CoreBundle/Provider/FailedEntriesProvider.php, src/SWP/Bundle/CoreBundle/Resources/config/controllers.yaml, src/SWP/Bundle/CoreBundle/Resources/config/services.yml
SWP-1911
- Added API to list items from the failure transport
=> Failure Queue API

.env, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/GeoIPBundle/DependencyInjection/Configuration.php
- use maxmind api (https://www.maxmind.com/en/account/login) to download geo ip database
=> use maxmind api to download geo ip database

src/SWP/Bundle/GeoIPBundle/Command/UpdateGeoIPDatabaseCommand.php
Fixes
Geo IP archive is a directory after de-compression now. Before it was just a file with the .mmdb extension. This Pr fixes database corruption error as it's not properly extracted.
- Extract tar.gz file, loop over the extracted files in the extracted directory to find the db file.
=> Properly download the geoip database

features/commands/organization_commands.feature, features/commands/tenant_commands.feature, src/SWP/Behat/Contexts/CommandContext.php, src/SWP/Bundle/CoreBundle/Command/CreateOrganizationCommand.php, src/SWP/Bundle/CoreBundle/Consumer/ImageConversionConsumer.php, src/SWP/Bundle/MultiTenancyBundle/Command/CreateOrganizationCommand.php, src/SWP/Bundle/MultiTenancyBundle/Command/CreateTenantCommand.php, src/SWP/Bundle/MultiTenancyBundle/Tests/Command/CreateOrganizationCommandTest.php, src/SWP/Component/MultiTenancy/Model/OrganizationInterface.php, src/SWP/Component/MultiTenancy/Model/TenantInterface.php
Improve default values for organization and tenants created with `--default` option
=> Default organization and tenant improvements

features/content_push/send_content_with_galleries_in_associations.feature, features/packages/get_packages.feature, src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Item.orm.yml, src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Item.yml, src/SWP/Bundle/ContentBundle/EventListener/ProcessArticleSlideshowsListener.php, src/SWP/Bundle/ContentBundle/Model/SlideshowItem.php, src/SWP/Bundle/ContentBundle/Model/SlideshowItemInterface.php, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/SlideshowItem.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.SlideshowItem.yml, src/SWP/Bundle/CoreBundle/Migrations/2020/03/Version20200305133408.php, src/SWP/Component/Bridge/Model/Item.php
SWP-1798
- add a position to slideshow items so it can be sorted in a proper order
=> add position to slideshows

features/packages/filtering_package_by_language.feature, src/SWP/Bundle/ElasticSearchBundle/Controller/Api/PackageSearchController.php, src/SWP/Bundle/ElasticSearchBundle/Repository/PackageRepository.php
Fixes #
SWP-1939
- allow filtering packages by language
=> allow filtering packages by language

features/content_push/check_article_body_via_webhook.feature, features/content_push/send_content_with_galleries_in_associations.feature, features/settings/listing_settings.feature, features/settings/restoring_settings_by_scope.feature, features/settings/updating_multiple_settings_at_once.feature, src/SWP/Bundle/CoreBundle/Controller/TenantController.php, src/SWP/Bundle/CoreBundle/Form/Type/TenantType.php, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Serializer/TenantHandler.php, src/SWP/Bundle/CoreBundle/Tests/Controller/SettingsControllerTest.php, src/SWP/Bundle/CoreBundle/Tests/Controller/TenantControllerTest.php, src/SWP/Bundle/CoreBundle/spec/Form/Type/TenantTypeSpec.php
Fixes #
SWP-1936
- add "default language" to tenant configuration
=> add "default language" to tenant configuration

features/content_push/validate_empty_headline.feature, src/SWP/Component/Bridge/Validator/NinjsValidator.php
=> set validator for headline min length

features/content_push/check_article_body_via_webhook.feature, features/content_push/send_content_with_galleries_in_associations.feature, features/settings/listing_settings.feature, features/settings/restoring_settings_by_scope.feature, features/settings/updating_multiple_settings_at_once.feature, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/SettingsBundle/Manager/SettingsManager.php
Related to https://github.com/superdesk/web-publisher/pull/1062
=> Fixed settings cache key, make default_language empty string

src/SWP/Bundle/TemplatesSystemBundle/.travis.yml
=> fix templates system bundle dependencies install test

src/SWP/Bundle/TemplatesSystemBundle/.travis.yml, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Component/TemplatesSystem/composer.json, src/SWP/Component/TemplatesSystem/spec/Gimme/Context/ContextSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Loader/ArticleLoaderSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Loader/ChainLoaderSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Loader/MemoryCachedLoaderSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Meta/MetaCollectionSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Meta/MetaSpec.php
=> fix spec namespaces, bump phpspec version

src/SWP/Bundle/TemplatesSystemBundle/.travis.yml, src/SWP/Bundle/TemplatesSystemBundle/composer.json, src/SWP/Component/TemplatesSystem/composer.json, src/SWP/Component/TemplatesSystem/spec/Gimme/Context/ContextSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Loader/ArticleLoaderSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Loader/ChainLoaderSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Loader/MemoryCachedLoaderSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Meta/MetaCollectionSpec.php, src/SWP/Component/TemplatesSystem/spec/Gimme/Meta/MetaSpec.php
=> Merge 2.1 to master

src/SWP/Bundle/ContentListBundle/.travis.yml, src/SWP/Bundle/MultiTenancyBundle/.travis.yml, src/SWP/Bundle/MultiTenancyBundle/composer.json, src/SWP/Bundle/SettingsBundle/.travis.yml
=> update bundles travis configs

src/SWP/Bundle/ContentListBundle/.travis.yml, src/SWP/Bundle/MultiTenancyBundle/.travis.yml, src/SWP/Bundle/SettingsBundle/.travis.yml
=> correctry change php memory limit in travis tests

features/commands/remove_missing_embedded_images.feature, src/SWP/Bundle/ContentBundle/Doctrine/ArticleRepositoryInterface.php, src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php, src/SWP/Bundle/CoreBundle/Command/RemoveMissingEmbeddedImagesCommand.php
=> add command to remove broken elements from articles body

features/commands/remove_missing_embedded_images.feature, src/SWP/Bundle/CoreBundle/Command/RemoveMissingEmbeddedImagesCommand.php
=> add limit parameter and better logging to broken embedded images remover

features/tenants/creating_a_new_tenant_with_apple_news_config.feature, src/SWP/Bundle/CoreBundle/Model/Tenant.php
=> Fixed setting apple news config

src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalyticsHandler.php, src/SWP/Bundle/CoreBundle/AnalyticsExport/ReportFileUploader.php
Fixes #
SWP-1931
- set the host of the analytics report URL based on the current tenant
=> set the host of the analytics report url

features/authors/delete_authors.feature, src/SWP/Bundle/ContentBundle/Controller/AuthorController.php, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/Article.orm.yml, src/SWP/Bundle/CoreBundle/Migrations/2020/04/Version20200406121345.php
- Added API endpoint to delete authors by id
=> delete authors API endpoint

composer.json, composer.lock
=> require symfony/proxy-manager-bridge intentionaly for prod

features/content_lists/do_not_add_articles_to_automatic_content_list.feature, features/content_lists/make_list_unlimited_with_limit_set_to_0.feature, src/SWP/Bundle/ContentListBundle/Remover/ContentListItemsRemover.php, src/SWP/Bundle/ContentListBundle/Services/ContentListService.php, src/SWP/Bundle/SettingsBundle/composer.json
Fixes ETWN-66 
Automatic content adds new article but removes previous ones
=> don't remove content list items when list is limited to 0

features/content_lists/pin_content_list_item_on_specific_position.feature, features/content_lists/pin_content_list_item_on_specific_position_in_automatic_list.feature, features/content_lists/pin_content_list_item_on_specific_position_in_manual_list.feature, src/SWP/Bundle/ContentListBundle/Form/Type/ContentListItemPositionType.php, src/SWP/Bundle/ContentListBundle/Resources/config/doctrine-orm/ContentListItem.orm.yml, src/SWP/Bundle/ContentListBundle/Resources/config/serializer/Model.ContentListItem.yml, src/SWP/Bundle/ContentListBundle/Services/ContentListService.php, src/SWP/Bundle/ContentListBundle/Services/ContentListServiceInterface.php, src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php, src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php, src/SWP/Bundle/CoreBundle/Form/Type/ContentListItemType.php, src/SWP/Bundle/CoreBundle/Migrations/2020/04/Version20200427121544.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/spec/EventListener/AddArticleToListListenerSpec.php, src/SWP/Bundle/CoreBundle/spec/Form/Type/ContentListItemTypeSpec.php, src/SWP/Component/ContentList/Model/ContentListAction.php, src/SWP/Component/ContentList/Model/ContentListItem.php
To allow pinning of articles in both automatic and manual lists on any position. User can pin or unpin article in any position. The number of articles that could be pinned in the lists should not be limited.
=> pin articles on any position in content lists

features/content_push/migrated_articles_redirects.feature, src/SWP/Bundle/CoreBundle/EventListener/MigratedArticleListener.php, src/SWP/Bundle/CoreBundle/Model/RedirectRouteInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml, src/SWP/Bundle/CoreBundle/Routing/MetaRouter.php, src/SWP/Bundle/RedirectRouteBundle/Model/RedirectRouteInterface.php
=> handle migrated article orginal url and redirect it to new article location

composer.json, composer.lock, features/content_lists/change_limit_of_content_lists.feature, features/content_lists/fill_list_with_latest_articles_when_no_criteria.feature, src/SWP/Behat/Contexts/Hook/DoctrineORMContext.php, src/SWP/Bundle/ContentBundle/composer.json, src/SWP/Bundle/CoreBundle/EventListener/UpdateContentListItemsListener.php, src/SWP/Component/Common/Model/DateTime.php, symfony.lock
On list update (with empty criteria) list should be filled with all tenant articles.
=> add latest articles to content list when filter is empty on list update

docs/manual/templates_system/articles.rst, docs/manual/templates_system/twig.rst, features/twig/get_origin_article_url.feature, src/SWP/Behat/Contexts/TemplatingContext.php, src/SWP/Bundle/ContentBundle/EventListener/ArticlePreviousRelativeUrlListener.php, src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php, src/SWP/Bundle/CoreBundle/EventListener/OverrideArticleSlugListener.php, src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml, src/SWP/Bundle/CoreBundle/Resources/config/twig.yml, src/SWP/Bundle/CoreBundle/Routing/MetaRouter.php, src/SWP/Bundle/CoreBundle/Twig/RedirectingExtension.php
=> introduce twig funtion for geting original url if article was renamed and slug was changed

src/SWP/Bundle/CoreBundle/AppleNews/Component/Body.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Caption.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Component.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/EmbedWebVideo.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/FacebookPost.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Figure.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/GalleryItem.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Heading.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Instagram.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Intro.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Photo.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Title.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Tweet.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/UrlAwareComponent.php, src/SWP/Bundle/CoreBundle/AppleNews/Converter/ArticleBodyToComponentsConverter.php, src/SWP/Bundle/CoreBundle/AppleNews/Converter/ArticleToAppleNewsFormatConverter.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/ArticleDocument.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/ComponentLayout.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/ComponentLayouts.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/ComponentTextStyle.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/ComponentTextStyles.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/LinkedArticle.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/Margin.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/Metadata.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/TextStyle.php, src/SWP/Bundle/CoreBundle/AppleNews/Serializer/AppleNewsFormatSerializer.php, src/SWP/Bundle/CoreBundle/Command/ConvertArticleToAppleNewsFormatCommand.php, src/SWP/Bundle/CoreBundle/Resources/config/apple_news.yaml
=> Apple news fixes

src/SWP/Bundle/CoreBundle/AppleNews/AppleNewsPublisher.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Byline.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Quote.php, src/SWP/Bundle/CoreBundle/AppleNews/Converter/ArticleBodyToComponentsConverter.php, src/SWP/Bundle/CoreBundle/AppleNews/Converter/ArticleToAppleNewsFormatConverter.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/ComponentLayouts.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/ComponentTextStyles.php, src/SWP/Bundle/CoreBundle/Command/ConvertArticleToAppleNewsFormatCommand.php, src/SWP/Bundle/CoreBundle/DependencyInjection/SWPCoreExtension.php, src/SWP/Bundle/CoreBundle/Resources/config/routers.yaml, src/SWP/Bundle/CoreBundle/Routing/TenantAwareAbsoluteUrlRouter.php
- fix URLs
- added quote
- added byline
=> Apple news quote, byline and url fixes

src/SWP/Bundle/CoreBundle/Controller/AuthController.php, src/SWP/Bundle/CoreBundle/EventListener/TenantNotFoundExceptionListener.php, src/SWP/Bundle/CoreBundle/Security/Authenticator/ExternalOauthAuthenticator.php, src/SWP/Bundle/CoreBundle/Tests/Controller/AuthControllerTest.php, src/SWP/Bundle/MultiTenancyBundle/Context/TenantContext.php, src/SWP/Bundle/MultiTenancyBundle/EventListener/TenantableListener.php, src/SWP/Bundle/MultiTenancyBundle/spec/Context/TenantContextSpec.php, src/SWP/Component/MultiTenancy/Exception/TenantNotFoundException.php, src/SWP/Component/MultiTenancy/Resolver/TenantResolver.php
=> improve errors messages for tenant not found and issues on connection with superdesk

src/SWP/Bundle/CoreBundle/Theme/Service/ThemeService.php
SWP-1961
- throw an exception instead of returning it
=> throw exception when theme installation fails

features/tenants/creating_a_new_tenant_with_apple_news_config.feature, src/SWP/Bundle/CoreBundle/Migrations/2020/06/Version20200629113833.php, src/SWP/Bundle/CoreBundle/Model/AppleNewsConfig.php, src/SWP/Bundle/CoreBundle/Model/AppleNewsConfigInterface.php, src/SWP/Bundle/CoreBundle/Model/Tenant.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/AppleNewsConfig.orm.yml
=> allow to reset apple news config

src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.BaseContent.yml
- Expose "place" in packages endpoint  
=> exposed place in packages listing

src/SWP/Bundle/CoreBundle/AppleNews/Component/Component.php, src/SWP/Bundle/CoreBundle/AppleNews/Component/Heading.php, src/SWP/Bundle/CoreBundle/AppleNews/Converter/ArticleBodyToComponentsConverter.php, src/SWP/Bundle/CoreBundle/AppleNews/Converter/ArticleToAppleNewsFormatConverter.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/ComponentLayouts.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/ComponentTextStyles.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/InlineTextStyle.php, src/SWP/Bundle/CoreBundle/AppleNews/Document/Metadata.php
=> apple news layout improvements

src/SWP/Bundle/CoreBundle/MessageHandler/ImageConversionHandler.php, src/SWP/Bundle/ElasticSearchBundle/Resources/config/app/config.yml
=> use throwable instead of exception, added retryOnConflict in ES config

src/SWP/Bundle/CoreBundle/Controller/MenuController.php, src/SWP/Bundle/MenuBundle/Doctrine/MenuItemRepositoryInterface.php, src/SWP/Bundle/MenuBundle/Doctrine/ORM/MenuItemRepository.php
=> allow to paginate the list of menus in API

src/SWP/Component/Bridge/Validator/NinjsValidator.php
=> delete the format from the scheme

src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php
=> fixed filtering by multiple services and subjects

src/SWP/Bundle/CoreBundle/EventListener/UpdatedPackageListener.php
=> check if metadata exist before removing

config/packages/messenger.yaml
=> configure messenger routing keys

features/content_lists/content_list_filtering_by_subjects.feature, src/SWP/Bundle/CoreBundle/Matcher/ArticleCriteriaMatcher.php
EWTN-146
- improved the way the article's metadata are matched against lists criteria/filters
=> improve article metadata matching against list criteria

features/content_push/check_article_body_via_webhook.feature, src/SWP/Bundle/ContentBundle/Processor/EmbeddedImageProcessor.php, src/SWP/Bundle/ContentBundle/Processor/EmbeddedImageProcessorInterface.php
Fixes #
- add copyright notice values to the web-publisher
=> FUN-34 - add copyright notice

src/SWP/Bundle/CoreBundle/Migrations/2020/09/Version20200901105137.php
=> added migration - route description field

src/SWP/Bundle/ContentBundle/DependencyInjection/Configuration.php, src/SWP/Bundle/ContentBundle/DependencyInjection/SWPContentExtension.php
=> Set media_storage_adapter based on env var

src/SWP/Bundle/CoreBundle/EventListener/FacebookInstantArticlesListener.php, src/SWP/Bundle/CoreBundle/Resources/config/services.yml
All articles added to the content list type = `bucket` are submitted to FBIA. Only articles which were marked to be published to FBIA should be submitted to FBIA.
=> publish articles to fbia when clearly stated

INSTALL.md, docs/cookbooks/developers/rules.rst, src/SWP/Bundle/FixturesBundle/Resources/themes/DefaultTheme/theme.json
Fixes #
updates rules documentation
=> updates rules documentation

src/SWP/Bundle/ContentBundle/Loader/ArticleAuthorLoader.php, src/SWP/Bundle/ContentBundle/Resources/config/services.yml
=> get the author with the most articles

src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalyticsHandler.php
- show `byline` field in the analytics reports
=> added byline to the analytics export

.travis.yml
composer 2.0 stable has been released. It is advised to make project use it.
=> Composer 2

src/SWP/Bundle/ContentBundle/Tests/Functional/EventListener/ProcessArticleMediaListenerTest.php
=> fix phpunit test in content bundle

src/SWP/Bundle/CoreBundle/GeoIp/CachedGeoIpChecker.php, src/SWP/Component/Bridge/Validator/NinjsValidator.php, src/SWP/Component/GeoIP/Reader/GeoIPReaderAdapter.php
- added article updated at timestamp to geo IP cache key
- added geonames props to place in ninjs schema
- always cast country and state to a string
=> added article updated at timestamp to geo ip cache key

src/SWP/Bundle/ContentBundle/EventListener/PopulateArticleAuthorSlugListener.php
newest composer updated started breaking behat tests, removal of old hack seems to fix it.
=> fix for timestampable composer update error

src/SWP/Bundle/CoreBundle/Migrations/2021/01/Version20210112135542.php, src/SWP/Bundle/CoreBundle/Migrations/2021/01/Version20210112135555.php
add fix for a migration extra fields
=> add fix for a migration extra fields

composer.json, composer.lock
Executing commands fails with `An option named "connection" already exists.` error.
- updated doctrine bundle to v 1.12.9
=> update doctrine bundle

features/redirect_routes/redirect_from_one_route_to_another.feature, src/SWP/Bundle/ContentBundle/Model/Route.php, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/RedirectRoute.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.Route.yml, src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/RouteControllerTest.php, src/SWP/Bundle/CoreBundle/Migrations/2021/01/Version20210112135542.php, src/SWP/Bundle/CoreBundle/Migrations/2021/03/Version20210330074519.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/RedirectRoute.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Route.orm.yml, src/SWP/Bundle/CoreBundle/Tests/Controller/ContentControllerTest.php
As a user, I should be able to see if the route is redirected to another one in the Routes management.
- expose redirects in the routes API endpoint
- fixed extra fields migration
=> expose redirects in routes API endpoint

features/bootstrap/AuthTokenContext.php, features/content_push/check_article_body_via_webhook.feature, features/content_push/send_content_with_galleries_in_associations.feature, features/tenants/creating_a_new_tenant_with_pwa_config.feature, features/user/register_and_login_with_PWA.feature, src/SWP/Bundle/CoreBundle/DependencyInjection/Compiler/OverrideEmailVerifierPass.php, src/SWP/Bundle/CoreBundle/Form/Type/PWAConfigType.php, src/SWP/Bundle/CoreBundle/Form/Type/TenantType.php, src/SWP/Bundle/CoreBundle/Migrations/2021/03/Version20210323112900.php, src/SWP/Bundle/CoreBundle/Migrations/Version20170301172303.php, src/SWP/Bundle/CoreBundle/Model/PWAConfig.php, src/SWP/Bundle/CoreBundle/Model/Tenant.php, src/SWP/Bundle/CoreBundle/Model/TenantInterface.php, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/PWAConfig.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/Tenant.orm.yml, src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.Tenant.yml, src/SWP/Bundle/CoreBundle/SWPCoreBundle.php, src/SWP/Bundle/CoreBundle/Util/VerifyEmailHelper.php, src/SWP/Bundle/CoreBundle/spec/Form/Type/TenantTypeSpec.php, src/SWP/Bundle/UserBundle/Controller/RegistrationController.php
To be able to add PWA specific configuration.
=> PWA config

src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleExtraEmbedField.orm.yml, src/SWP/Bundle/ContentBundle/Resources/config/doctrine-orm/ArticleExtraTextField.orm.yml, src/SWP/Bundle/CoreBundle/Migrations/2021/04/Version20210426085015.php, src/SWP/Bundle/ElasticSearchBundle/Controller/Api/PackageSearchController.php, src/SWP/Component/Bridge/Validator/NinjsValidator.php
=> SD v2 compatibility

src/SWP/Bundle/ContentBundle/Model/Article.php
Article corrections did not work.
Casted integer value to string 
=> Cast integer value to string

.gitignore, composer.json, composer.lock, src/SWP/Bundle/ContentBundle/Asset/GoogleAssetUrlGenerator.php, src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php, src/SWP/Bundle/ContentBundle/DependencyInjection/Configuration.php, src/SWP/Bundle/ContentBundle/DependencyInjection/SWPContentExtension.php, src/SWP/Bundle/ContentBundle/Factory/GCSClientFactory.php, src/SWP/Bundle/ContentBundle/Manager/MediaManager.php, src/SWP/Bundle/ContentBundle/Resources/config/app/config.yml, src/SWP/Bundle/ContentBundle/Resources/config/asset_gcs_storage.yaml
=> Swp 2195 gcs

src/SWP/Bundle/CoreBundle/EventListener/OverrideArticleSlugListener.php, src/SWP/Bundle/CoreBundle/Service/ArticlePublisher.php
=> Remove unnececary previous route duplication on article update

src/SWP/Bundle/CoreBundle/Controller/AuthController.php, src/SWP/Bundle/UserBundle/Controller/RegistrationController.php, src/SWP/Bundle/UserBundle/Security/UserProvider.php
=> Security core componet changes
