superdesk/web-publisher

web/app.php

See the performance improvements with APC (APCu) enabled, on each request.
This can be achived also, by running command:
```bash
composer dump-autoload --optimize
```
but also there should be the possibility to cache Autoloader automatically when apc or xcache is enabled for better performance.
See http://symfony.com/doc/current/book/performance.html as a reference.

added possibility to cache Autoloader with APC or XCache

---

composer.json

excludes not needed tests/specs files from classmap, useful in prod env as we don't need there tests
I would suggest to add this option to every bundle/component we created.

add composer exclude-from-classmap

---

.travis.yml
app/check.php
composer.json
composer.lock
src/SWP/Bundle/BridgeBundle/Client/GuzzleApiClient.php
src/SWP/Bundle/BridgeBundle/Client/GuzzleClient.php
src/SWP/Bundle/BridgeBundle/Controller/BridgeController.php
src/SWP/Bundle/BridgeBundle/DependencyInjection/Configuration.php
src/SWP/Bundle/BridgeBundle/DependencyInjection/SWPBridgeExtension.php
src/SWP/Bundle/BridgeBundle/SWPBridgeBundle.php
src/SWP/Bundle/BridgeBundle/Tests/DependencyInjection/SWPBridgeExtensionTest.php
src/SWP/Bundle/BridgeBundle/spec/Client/GuzzleApiClientSpec.php
src/SWP/Bundle/BridgeBundle/spec/Client/GuzzleClientSpec.php

| BC breaks?    | yes
| Fixed tickets | -
Security support for PHP 5.5 is ending in 1 month, thus we should drop support for it in Web Publisher.
See http://php.net/supported-versions.php
This PR is related to https://github.com/superdesk/web-publisher/pull/72 as some dependencies were failing on PHP 5.5 because of not supported PHP 5.5 version.

[Composer][Travis] Drop PHP version 5.5, travis improvements

---

AUTHORS.md
src/SWP/Bundle/FixturesBundle/Command/ThemeSetupCommand.php
src/SWP/Bundle/MultiTenancyBundle/Command/CreateTenantCommand.php
src/SWP/Bundle/MultiTenancyBundle/Repository/TenantRepository.php
src/SWP/Component/MultiTenancy/Model/TenantInterface.php

| Bug fix?      | [yes]
| Fixed tickets | [SWP-189]
By default, the default theme is now assigned to the default tenant by the theme:setup command. If there is no default tenant, an exception will be thrown, and the user will be prompted to run the swp:tenant:create command.

Default theme assigned to default tenant by theme setup command

---

composer.json
composer.lock
docs/templates_system/templates.rst
src/SWP/Bundle/TemplateEngineBundle/Controller/ContainerController.php
src/SWP/Bundle/TemplateEngineBundle/Resources/config/services.yml
src/SWP/Bundle/WebRendererBundle/Resources/config/services.yml
src/SWP/Bundle/WebRendererBundle/Tests/Twig/StringyExtensionTest.php
src/SWP/Bundle/WebRendererBundle/Twig/StringyExtension.php

| Bug fix?      | [yes]
| New feature?  | [yes]
| Fixed tickets | [SWP-235]
All functions in this Stringy library (https://github.com/danielstjules/Stringy) have been made available in twig. Functions which manipulate strings are available as filters, while functions which return booleans are available as functions. So, {{ value|camelize }} will render the value in camel case, while {% if hasUpperCase(value) %} will be true if the value has any upper case character.

Implemented twig extension for Strings library

---

src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php
src/SWP/Bundle/ContentBundle/Tests/Loader/ArticleLoaderTest.php

| Bug fix?                  | [yes]
| New feature?              | [no]
| BC breaks?                | [no]
| Deprecations?             | [no]
| Tests pass?               | [yes]
| Changelog update required | [no]
| Fixed tickets             | [SWP-270]
Fixes use of 'order by' with a parameter other than id when loading articles in a template

Article loader fix

---

app/config/config.yml
src/SWP/Bundle/CoreBundle/EventSubscriber/HttpCacheSubscriber.php
src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Component/Common/Event/HttpCacheEvent.php

Revert HttpCache subscriber so we can manual control on http cache invalidation. For example we use it now in Containers.

Revert HttpCacheSubscriber

---

CHANGELOG.md
src/SWP/Bundle/ContentBundle/Rule/Applicator/ArticleRuleApplicator.php
src/SWP/Bundle/ContentBundle/spec/Rule/Applicator/ArticleRuleApplicatorSpec.php
src/SWP/Bundle/CoreBundle/Tests/Controller/ArticleAutoPublishTest.php

| Fixed tickets             | SWP-561
Before it was possible to do it but only manually via API for routes. Right now article will be assigned to route (of type `content`) automatically once the article will be published

Content is not automatically assigned to route of type 'content'

---

src/SWP/Bundle/CoreBundle/Model/ArticleMedia.php
src/SWP/Bundle/CoreBundle/Model/ArticleMediaInterface.php
src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
src/SWP/Bundle/CoreBundle/Resources/config/doctrine-orm/ArticleMedia.orm.yml
src/SWP/Bundle/CoreBundle/spec/Model/ArticleMediaSpec.php

Article media should be tenant aware, it means that every tenant should have its own media for every article.

make article media tenant aware

---

CHANGELOG.md
docs/cookbooks/developers/content_lists.rst
docs/cookbooks/editors/adding_menu.rst
docs/cookbooks/editors/index.rst
src/SWP/Bundle/CoreBundle/Controller/MenuController.php
src/SWP/Bundle/CoreBundle/EventListener/MenuWidgetCreateListener.php
src/SWP/Bundle/CoreBundle/EventListener/MenuWidgetDeleteListener.php
src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/Tests/Controller/MenuControllerTest.php
src/SWP/Bundle/CoreBundle/spec/EventListener/MenuWidgetCreateListenerSpec.php
src/SWP/Bundle/CoreBundle/spec/EventListener/MenuWidgetDeleteListenerSpec.php
src/SWP/Bundle/MenuBundle/MenuEvents.php
src/SWP/Bundle/TemplatesSystemBundle/DependencyInjection/Configuration.php
src/SWP/Bundle/TemplatesSystemBundle/Form/Type/WidgetType.php
src/SWP/Bundle/TemplatesSystemBundle/Model/WidgetModel.php
src/SWP/Bundle/TemplatesSystemBundle/Repository/WidgetModelRepository.php
src/SWP/Component/Common/Exception/UnexpectedTypeException.php
src/SWP/Component/TemplatesSystem/Gimme/Model/WidgetModelInterface.php
src/SWP/Component/TemplatesSystem/Tests/Gimme/Model/WidgetModel.php

| Fixed tickets             | SWP-563
TODO:

Automatically create menu widget when root menu/navigation is created

---

src/SWP/Bundle/CoreBundle/Controller/MenuController.php
src/SWP/Bundle/CoreBundle/Manager/MenuItemManager.php
src/SWP/Bundle/CoreBundle/Model/MenuItem.php
src/SWP/Bundle/CoreBundle/Model/MenuItemInterface.php
src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/spec/Manager/MenuItemManagerSpec.php
src/SWP/Bundle/MenuBundle/Form/Type/MenuType.php
src/SWP/Bundle/MenuBundle/Manager/MenuItemManager.php
src/SWP/Bundle/MenuBundle/spec/Manager/MenuItemManagerSpec.php

| Fixed tickets             | SWP-564, SWP-587
Route has a precedense before the uri, i.e. if route is set and you want to set custom uri, you need to first unassign route so the uri can take the precedense.

extend menu manager, assign route's url

---

src/SWP/Bundle/ContentListBundle/Doctrine/ORM/ContentListRepository.php
src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php
src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/spec/EventListener/AddArticleToListListenerSpec.php
src/SWP/Component/ContentList/Repository/ContentListRepositoryInterface.php

| Fixed tickets             | SWP-740
Articles, when they are published, should be added to automatic content lists and to the buckets only, not to the manual lists.

SWP- 740 - fixed issue with adding articles to content list on publish

---

src/SWP/Bundle/CoreBundle/Widget/ContentListWidget.php
src/SWP/Bundle/CoreBundle/spec/Widget/ContentListWidgetSpec.php

| Fixed tickets             | SWP-607
DEPRECATION:
From now you should use manual fetching content list items in content list widget templates. Content list loader is much more powerful than iteration on raw list data.
Documentation for content list items loader is here: http://superdesk-publisher.readthedocs.io/en/latest/manual/templates_system/content_list.html

Pass List Id to content list widget

---

CHANGELOG.md
app/Resources/views/widgets/liveblog.html.twig
docs/cookbooks/developers/widgets.rst
src/SWP/Bundle/CoreBundle/Fragment/ExternalEsiFragmentRenderer.php
src/SWP/Bundle/CoreBundle/Fragment/ExternalFragmentRenderer.php
src/SWP/Bundle/CoreBundle/Model/WidgetModel.php
src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/Tests/Fragment/ExternalFragmentRendererTest.php
src/SWP/Bundle/CoreBundle/Tests/Functional/ArticleTitleChangeTest.php
src/SWP/Bundle/CoreBundle/Tests/Functional/Resources/db.json
src/SWP/Bundle/CoreBundle/Tests/Functional/Resources/routes.json
src/SWP/Bundle/CoreBundle/Widget/LiveblogWidgetHandler.php
src/SWP/Bundle/CoreBundle/spec/Widget/LiveblogWidgetHandlerSpec.php

add liveblog widget, implement externall esi renderer (fallback to curl when no ESI support)

---

CHANGELOG.md
app/phpunit.xml.dist
src/SWP/Bundle/CoreBundle/Form/Type/TenantType.php
src/SWP/Bundle/CoreBundle/Tests/Controller/TenantControllerTest.php
src/SWP/Bundle/CoreBundle/spec/Form/Type/TenantTypeSpec.php

[BC Break] Change in create tenant API endpoint - tenant domainName is now required. 

[BC Break] make tenant sudbomain optional, and domain required, fix tests

---

app/migrations/Version20170831132632.php
src/SWP/Bundle/MultiTenancyBundle/Resources/config/doctrine-orm/Tenant.orm.yml

When a tenant with, for example, name "test" is removed, and you want to create another tenant with the same name under the same organization, API throws 500 error because it still detects that tenant with subdomain "test" exists in the database even if it was flagged as deleted.
The deleted tenant should not be taken into consideration, instead, a new tenant with the same subdomain should be created because the previous one was deleted and the deleted tenants can not be re-activated. …

fixed index for tenant table

---

CHANGELOG.md
app/migrations/Version20180223095718.php
docs/conf.py
docs/manual/templates_system/routes.rst
features/routes/management.feature
features/twig/listing_route_by_slug.feature
features/twig/listing_route_by_slug_and_parent.feature
src/SWP/Bundle/ContentBundle/Loader/RouteLoader.php
src/SWP/Bundle/ContentBundle/Model/RouteInterface.php
src/SWP/Bundle/ContentBundle/Model/RouteTrait.php
src/SWP/Bundle/ContentBundle/Service/RouteService.php
src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/RouteControllerTest.php
src/SWP/Bundle/ContentBundle/Tests/Functional/app/Resources/fixtures/separate_article.yml
src/SWP/Bundle/ContentBundle/spec/Service/RouteServiceSpec.php
src/SWP/Bundle/CoreBundle/Tests/Controller/ContentControllerTest.php
src/SWP/Bundle/CoreBundle/Tests/Fixtures/themes/123abc/theme_test/views/route_by_slug_and_parent.html.twig

| Fixed tickets             | SWP-1061
TODO:

Generate route's slug based on route's name if not provided by default

---

docs/manual/themes/theme_settings.rst
src/SWP/Bundle/CoreBundle/Resources/config/twig.yml
src/SWP/Bundle/CoreBundle/Twig/ThemeExtension.php

| Fixed tickets             | SWP-1102

Missing setting in theme.json should not break pages in prod

---

src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/Theme/Asset/AssetsInstaller.php
src/SWP/Bundle/CoreBundle/Theme/Installer/TenantAwareThemeInstaller.php

- don't create 'theme' dir when installing assets, 
- make theme assets path absolute

don't create 'theme' dir when installing assets, absolute dirs

---

src/SWP/Bundle/ContentBundle/EventListener/LinkRequestListener.php
web/app_dev.php

| Changelog update required   no

[fix] use X_FORWARDED_HOST when exists as server name in sub requests

---

src/SWP/Bundle/ContentBundle/Controller/RouteController.php
src/SWP/Bundle/ContentBundle/EventListener/RouteRemoveListener.php
src/SWP/Bundle/ContentBundle/Resources/config/services.yml
src/SWP/Bundle/ContentBundle/RouteEvents.php
src/SWP/Bundle/ContentBundle/Tests/Functional/Controller/RouteControllerTest.php
src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php
src/SWP/Bundle/CoreBundle/EventListener/RouteRemoveListener.php
src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListItemControllerTest.php
src/SWP/Bundle/CoreBundle/Tests/Controller/RouteControllerTest.php

| Fixed tickets             | SWP-1145
From now before removing route user will need to remove all child routes first.

[improvement] on route remove unpublish articles (status new) and package (status usable)

---

src/SWP/Bundle/CoreBundle/Controller/AuthController.php
src/SWP/Bundle/CoreBundle/Tests/Controller/AuthControllerTest.php

| Bug fix?                  | yes|
| New feature?              |no
| BC breaks?                |no
| Deprecations?             |no
| Fixed tickets             | #562 
Hi. First time adding to Publisher so I hope it's ok. It adds compatibility to allow a single superdesk server to be written into the parameters.yml file, as I experienced a bug related to it [here](https://github.com/superdesk/web-publisher/issues/562).

Fixed handling of a single superdesk server in parameters.yml

---

docs/manual/templates_system/articles.rst
docs/manual/templates_system/content_list.rst
src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php
src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php
src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleLoaderTest.php

| Fixed tickets             | SWP-1302
Filtering out selected articles (useful when you want to exclude articles listed already in content list)
```
{% gimmelist article from articles without {article:[1,2]} %} 
% endgimmelist %}
```
```
{% gimmelist article from articles without {article:[gimme.article]} %} 
{% endgimmelist %}
```

[improvement] add exclude_article handling to article loader

---

docs/manual/templates_system/routes.rst
src/SWP/Bundle/ContentBundle/Doctrine/ORM/RouteRepository.php
src/SWP/Bundle/ContentBundle/Loader/RouteLoader.php
src/SWP/Bundle/ContentBundle/Model/RouteRepositoryInterface.php
src/SWP/Bundle/ContentBundle/Tests/Functional/RouteLoaderTest.php

| Fixed tickets             | SWP-1306
Listing a Routes Collection
---------------------------
Usage:
```
<ul>
{% gimmelist route %}
<li>{{ route.name }}
{% endgimme %}
</ul>
```
```
<ul>
{% gimmelist route with {parent: 5} %} 
<li>{{ route.name }}
{% endgimme %}
</ul>
```

[feature] add collection loading to route loader

---

features/content_push/send_content_with_embedded_audio.feature
src/SWP/Bundle/ContentBundle/Manager/MediaManager.php

Store `mp3` files with `mp3` extension, not with `mpga`

save mp3 files with mp3 extension instead of mpga

---

CHANGELOG.md
features/content_push/correcting_published_package.feature
features/content_push/correcting_slugline_of_published_package.feature
features/settings/listing_settings.feature
features/settings/restoring_settings_by_scope.feature
features/settings/updating_multiple_settings_at_once.feature
src/SWP/Bundle/CoreBundle/EventListener/OverrideArticleSlugListener.php
src/SWP/Bundle/CoreBundle/Resources/config/app/config.yml
src/SWP/Bundle/CoreBundle/Resources/config/services.yml

By setting `override_slug_on_correction` setting to `true` it is possible to override article's slug on article correction.

Allow to change the article's slug based on settings

---

features/twig/loaders/content_list_items_loader.feature
src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php
src/SWP/Bundle/ContentBundle/Provider/ORM/ArticleProvider.php
src/SWP/Bundle/ContentBundle/Tests/Functional/Loader/ArticleLoaderTest.php
src/SWP/Bundle/CoreBundle/Checker/AmpSupportChecker.php
src/SWP/Bundle/CoreBundle/Enhancer/RouteEnhancer.php

fix article loader when slug is provided by is empty string

---

features/settings/updating_multiple_settings_at_once.feature
src/SWP/Bundle/SettingsBundle/Manager/SettingsManager.php
src/SWP/Bundle/SettingsBundle/Tests/Functional/Controller/SettingsControllerTest.php
src/SWP/Component/Seo/Model/SeoMetadata.php

Empty value for theme setting of type 'string' cannot be saved

---

src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php
src/SWP/Bundle/CoreBundle/Twig/RoutingExtension.php

Don't reject job from queue when entity manager is closed, don't break page when url generation have invalid parameters

Fix handling exceptions

---

features/02_articles/analytics.feature
src/SWP/Bundle/CoreBundle/Consumer/AnalyticsEventConsumer.php
src/SWP/Bundle/CoreBundle/Resolver/ArticleResolver.php
src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/Service/ArticleStatisticsService.php
src/SWP/Bundle/CoreBundle/Tests/Twig/ArticleEventsExtensionTest.php
src/SWP/Bundle/CoreBundle/Twig/ArticleEventsExtension.php
src/SWP/Bundle/CoreBundle/spec/Consumer/AnalyticsEventConsumerSpec.php

- use `LOCK TABLE swp_article_statistics IN EXCLUSIVE MODE;` to eliminate database deadlocks for concurrent processes
- increase impressions and pageviews count using DQL
- added caching

impressions performance improvements

---

src/SWP/Bundle/CoreBundle/Model/ContentList.php
src/SWP/Bundle/CoreBundle/Model/ContentListInterface.php
src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.ContentList.yml
src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/Serializer/ContentListSerializationSubscriber.php
src/SWP/Bundle/CoreBundle/Tests/Controller/ContentListControllerTest.php

Fixed tickets : SWP-1710
In content list data we have now `latest_items` with first 5 items ordered by createdAt (`desc`).

add latest items to content list serialized data in api

---

src/SWP/Bundle/CoreBundle/Controller/ExternalOauthController.php
src/SWP/Bundle/CoreBundle/Resources/config/controllers.yaml
src/SWP/Bundle/CoreBundle/Security/Authenticator/ExternalOauthAuthenticator.php

set jwt token in cookie on oauth success login to be able to get user profile/settings data from API.

set jwt token in cookie on oauth success login

---

config/packages/dev/monolog.yaml
config/packages/prod/monolog.yaml

Fixes:
Issue with production failing when correct graylog instance data are not set
- log this same data to graylog and filesystem 
- log app channel data only when error level message i raised

log this same (and more) data to filesystem and graylog

---

composer.lock

Fixes `Undefined index: server_url` warnings.

updated amp lib with a fix for the server_url warnings

---

src/SWP/Bundle/CoreBundle/Hydrator/PackageHydrator.php
src/SWP/Bundle/CoreBundle/Resources/config/services.yml

Changing default dir `/tmp` to `var/cache` in PackageHydrator.

set generated classes target dir to var/cache in PackageHydrator

---

features/content_push/check_article_body_via_webhook.feature
src/SWP/Bundle/ContentBundle/Processor/EmbeddedImageProcessor.php
src/SWP/Bundle/ContentBundle/Tests/Functional/EventListener/ProcessArticleMediaListenerTest.php

| New feature?  | yes
| Fixed tickets | 
It adds the attribute "loading" with the value "lazy" on all embedded images.
To ensure the speediest page load possible we can use the new "loading" attribute to lazy load images on the page: https://web.dev/native-lazy-loading/
Publish an article with an embedded image and verify that it has the attribute "loading" with the value "lazy".
The "loading" attribute is currently only supported in Chrome. All other browsers will ignore it but are currently working on implementing support.
- [Firefox support bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1542784)
- [WebKit support …

Add lazy load attribute to embedded images

---

app/Resources/meta/route.yml
src/SWP/Bundle/CoreBundle/Tests/Loader/ArticleLoaderTest.php

Fixes SWP-1788
- expose `article.route.parent` (and `route.parent`)

expose route parent for templators

---

src/SWP/Bundle/TemplatesSystemBundle/Loader/TraceableChainLoader.php

Fixes problem with profile serialization with complex parameters passed to loaders used on page

[fix] safely save loader parameters

---

src/SWP/Bundle/ContentBundle/Resolver/AssetLocationResolver.php
src/SWP/Bundle/CoreBundle/Twig/Cache/KeyGenerator/TenantAwareMetaKeyGenerator.php
src/SWP/Bundle/CoreBundle/Twig/Cache/Strategy/LifetimeCacheStrategy.php
src/SWP/Bundle/CoreBundle/Twig/Cache/Strategy/TagAwareIndexedChainingCacheStrategy.php
src/SWP/Bundle/FixturesBundle/DataFixtures/ORM/LoadArticlesData.php
src/SWP/Bundle/FixturesBundle/Resources/fixtures/ORM/dev/article.yml
symfony.lock

- remove cache key md5 hashing, make sure that annotations are hashed in generational and lifetime strategies
- don't use aws prefix if not set
- limit number of articles in dev fixtures

Improve twig cache key generation

---

features/content_lists/add_article_to_automatic_list_after_update.feature
src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php
src/SWP/Bundle/CoreBundle/EventListener/AddArticleToListListener.php
src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/spec/EventListener/AddArticleToListListenerSpec.php

Use case: On first publish action editor forgot to set correct keywords in article, he does that with correction and then article should be added to matching content list
Fixes # SWP-1840

add article to matching content list after correction

---

features/twig/loaders/exclude_articles_by_routes.feature
src/SWP/Bundle/ContentBundle/Doctrine/ORM/ArticleRepository.php
src/SWP/Bundle/ContentBundle/Loader/ArticleLoader.php

SWP-1854
This PR adds a new feature which allows excluding articles by route ids in twig templates.
Usage:
```twig
{% gimmelist article from articles without { route: [2] } %}
{{ article.title }}-{{ article.id }}-{{ article.route.name }}
{% endgimmelist %}
```

exclude articles by routes

---

src/SWP/Bundle/CoreBundle/Serializer/TenantHandler.php
src/SWP/Bundle/CoreBundle/spec/Serializer/TenantHandlerSpec.php

Fixes broken filtering of content lists and routes in tenant response

enable tenantable before fetching content_lists and routes for tenant

---

features/02_articles/validating_article_slugline.feature
features/content_lists/add_article_to_automatic_list_after_update.feature
src/SWP/Bundle/BridgeBundle/EventListener/ValidationListener.php
src/SWP/Bundle/ContentBundle/Model/Article.php
src/SWP/Bundle/CoreBundle/Consumer/ContentPushConsumer.php

* use title when slugline is set to empty string
* reset entity manager when exception is cached in content push consumer

handle items with slugline property set to empty string

---

features/02_articles/searching_articles_by_authors.feature
src/SWP/Bundle/ElasticSearchBundle/Repository/ArticleRepository.php
src/SWP/Bundle/ElasticSearchBundle/Resources/config/app/config.yml

Improved articles search by authors.
For example, there are two authors with names: `John Doe` and `John Doe Second`. 
When searching for `John` no results will be returned.
When searching for `John Doe Second` the articles by `John Doe Second` will only be returned.
When searching for `John Doe` the articles by `John Doe` will only be returned.
- Search articles by exact author-name

search articles by exact author name

---

src/SWP/Bundle/CoreBundle/Security/Authenticator/TokenAuthenticator.php
src/SWP/Bundle/CoreBundle/Tests/ContentPushTest.php

When the basic auth was enabled on the server-side, the Publisher was returning `{“status”:403,“message”:“Username could not be found.“}` error on all routes because the Authorization header was added by enabling the basic auth.
TokenAuthorization should be supported only in the API.

Support Token Authenticator only in the API

---

src/SWP/Bundle/CoreBundle/EventListener/ImageToWebpConversionListener.php

make sure that image conversion is handled also in production consumer environment where termination event is not fired

fix image processing on production

---

src/SWP/Bundle/CoreBundle/AnalyticsExport/ExportAnalyticsHandler.php

Fixes #
SWP-1927
- when start and end params are not provided it should fallback to null by default so the articles are loaded based on other criteria

fixed date times when null and export only published articles

---

config/packages/dev/messenger.yaml

use sync queues in dev env - so rabbit mq instance is not needed locally and in publisher ci tests 

use sync queues in dev env

---

docs/cookbooks/developers/content_lists.rst
features/content_lists/add_article_to_list_based_on_unordered_subjects.feature
src/SWP/Bundle/CoreBundle/Filter/DataFilter.php
src/SWP/Bundle/CoreBundle/Filter/Exception/FilterException.php
src/SWP/Bundle/CoreBundle/Filter/Exception/KeyNotExistsException.php
src/SWP/Bundle/CoreBundle/Filter/Exception/NotEqualDataException.php
src/SWP/Bundle/CoreBundle/Matcher/ArticleCriteriaMatcher.php
src/SWP/Bundle/CoreBundle/Tests/FIlter/DataFilterTest.php
src/SWP/Component/ContentList/Model/ContentList.php

Allow to catch published article to content list by expression filter.
```
{"metadata": "filter.contains('subject').containsItem('code', '001').containsItem('code', '123')"}
```

add option to filter article metadata with expression

---

composer.lock

`amp-web-push` component is omitted when rendering amp page. 
- added support to `amp-web-push` in the external lib and update that dependency

upgrade amp lib to include amp-web-push component

---

src/SWP/Bundle/CoreBundle/Controller/ContentController.php
src/SWP/Bundle/CoreBundle/Controller/DefaultController.php

Do not blindly trust http `Accept` header and built in symfony content negotiation. Instead of that explicitly se content type header in response.

set text/html as default response content type for template rendering result

---

app/Resources/meta/seoMetadata.yml

Rendering `twitterMedia` and `ogMedia` returned null values, thus it was not possible to generate the URL for those images using, e.g. `{{url(gimme.article.seoMetadata.twitterMedia)}}`
- expose twitterMedia and ogMedia values in the seoMetadata object in twig

expose twitterMedia and ogMedia values in the seoMetadata object in twig

---

src/SWP/Bundle/CoreBundle/Controller/ExternalOauthController.php

Fixes #1115 
- Start a session to keep track of a route that a user can be redirected to after a successful login
Currently, after a successful login, the user is always redirected to the 'homepage' route. It would be nice if users were redirected back to an article if they started the login flow from an article.
Create a link to the oauth route with the query param `redirect_to_route_when_successful`.
```twig
<a href="{{ path('connect_oauth_start', {'redirect_to_route_when_successful': path(gimme.article)}) }}">Login</a></p>
```

Redirect to dynamic route after successful login

---

src/SWP/Bundle/BridgeBundle/Resources/config/doctrine-orm/Item.orm.yml
src/SWP/Bundle/CoreBundle/Migrations/2020/07/Version20200706135942.php

- change the headline of the item to `text` because the headline can be longer than the default 255 chars limit.

change item headline to text

---

src/SWP/Bundle/ContentBundle/Resources/config/asset_aws_storage.yaml

Because of the invalid parameters passed to the was URL generator class, the URLs to assets hosted on AWS were generated wrongly.

fixed aws url generator

---

src/SWP/Bundle/CoreBundle/Resources/config/services.yml
src/SWP/Bundle/CoreBundle/Service/FacebookInstantArticlesService.php
src/SWP/Bundle/CoreBundle/Tests/Service/FacebookInstantArticlesServiceTest.php

When submitting the article to FBIA fails for a random reason the article won't be published at all on the website.
- When the FB could not be reached or there is an error from the FB API, skip adding the article to the FBIA and log the exception message.

Catch FBIA exceptions

---

features/twig/loaders/searchresults_loader.feature
features/twig/loaders/searchresults_loader_term_suggest.feature
src/SWP/Bundle/ElasticSearchBundle/Loader/SearchResultLoader.php
src/SWP/Bundle/ElasticSearchBundle/Repository/ArticleRepository.php

Provides fuzzy search term fixing. 
When elastic search finds better phrase it is provided to the user.
In  template it can be then use like this: 
```
Did you mean <a href="{{ path(app.request.attributes.get('_route'),
app.request.query.all|merge({'q': searchResults.suggestedTerm}))|replace({'%20': '+'})  }}">{{ searchResults.suggestedTerm }}</a> ?
```

Term suggest

---

public/index.php

Properly detect client real IP in Publisher for the geolocation feature. When the app is behind the proxy the real client IP address is the IP of the proxy.
- set value of `x-forwarded-for` header from `x-real-ip` header

set x-forwarded-for from x-real-ip header

---

features/02_articles/article_attach_to_content_route.feature
src/SWP/Bundle/ContentBundle/EventListener/AttachArticleToContentRouteListener.php
src/SWP/Bundle/ContentBundle/Resources/config/services.yml
src/SWP/Bundle/ContentBundle/spec/EventListener/AttachArticleToContentRouteListenerSpec.php

Fixes #
When publishing an article to content type of route, we also need to assign its id to route's 'content' property. 
Only then that article appears on frontend as content of that route.

Attach article to content route on article publish

---

public/index.php
src/SWP/Bundle/CoreBundle/MessageHandler/AnalyticsEventHandler.php
src/SWP/Bundle/CoreBundle/Resources/config/message_handlers.yaml
src/SWP/Bundle/CoreBundle/Service/ArticleStatisticsService.php

_swp_analytics endpoint was broken for new pageviews and articles were not sorted correctly by pageviews because of elasticsearch index not being updated on pageview update

Fix _swp_analytics endpoint and sorting by page views

---

src/SWP/Bundle/ElasticSearchBundle/Repository/PackageRepository.php
src/SWP/Bundle/ElasticSearchBundle/Resources/config/app/config.yml

Searching by phrases that contain diacritical marks doesn't work.
For example, typing a phrase with `à` will not return any results in the packages search API.
Apply `swp_folding_analyzer` analyzer to package fields in ES mapping to drop the diacritical marks

ES- Added asciifolding analyzer to package fields

---

src/SWP/Bundle/CoreBundle/MessageHandler/AbstractContentPushHandler.php
src/SWP/Bundle/CoreBundle/MessageHandler/Exception/LockConflictedException.php
src/SWP/Bundle/CoreBundle/MessageHandler/ImageConversionHandler.php
src/SWP/Bundle/CoreBundle/Resources/config/message_handlers.yaml

It should not be possible to modify the same article once it's being processed by one of the workers. Currently, the webp images are processed concurrently and one process tries to update the same article but its version is older than the one in the elasticsearch, thus it results in throwing errors on the elasticsearch `version conflict, current version [8] is different than the one provided [7]` causing the delays in showing up the articles in the ES index.
- force retry when the lock is already acquired by one of the processes.

force retry when the lock is aquired

---

src/SWP/Bundle/ContentBundle/Manager/MediaManager.php

`guessExtension` doesn't guarantee the returned extension. For some of the images, it can't guess it and the function returns null although it expects a string.
- `getClientOriginalExtension` as a file extension fallback 

get client original extension from file as a fallback

---

src/SWP/Bundle/ElasticSearchBundle/Repository/PackageRepository.php
src/SWP/Component/Bridge/Model/License.php

- assign weights properly
- allow returning null values for license name and URL when it's not set

Fixed ES weights & license fixes

---

composer.json
composer.lock
config/packages/security_checker.yaml
symfony.lock

Symfony built-in security checker has been deprecated

update liip rmt lib

---

config/packages/security.yaml
features/search/public_search_api_endpoint.feature
src/SWP/Bundle/BridgeBundle/Resources/config/serializer/Model.Author.yml
src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.Article.yml
src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.ArticleAuthor.yml
src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.ArticleMedia.yml
src/SWP/Bundle/ContentBundle/Resources/config/serializer/Model.Route.yml
src/SWP/Bundle/CoreBundle/Controller/ContentListItemController.php
src/SWP/Bundle/CoreBundle/Resources/config/serializer/Model.Article.yml
src/SWP/Bundle/ElasticSearchBundle/Controller/Api/ArticleSearchController.php
src/SWP/Bundle/ElasticSearchBundle/Controller/Api/PublicArticleSearchController.php
src/SWP/Bundle/ElasticSearchBundle/Resources/config/controllers.yaml

Too much data were exposed from the internal API which was not needed. It was also possible to search for unpublished articles and search with more criteria.
- limited querying the public search API endpoint
- limit data returned by the search API endpoint
- renamed endpoint

limit querying public search API endpoint

---

src/SWP/Bundle/CoreBundle/MessageHandler/ImageConversionHandler.php

`ImageConversionHandler.php` would crash on images in the color space _Adobe RGB (1998)_ with the error: `Paletter image not supported by webp`.
Normalize the color space to truecolor before converting it to webp.

Convert image palette to truecolor before converting to webp

---

src/SWP/Bundle/CoreBundle/Provider/CachedSubscriptionsProvider.php

`CachedSubscriptionsProvider` will throw an error when the generated cache key contains a space.
```
Doctrine\Common\Cache\InvalidCacheId: Cache id "/var/www/publisher[subscription_provider_xxxxtest@example.com__NAME WITH SPACE][1]" contains unauthorized character " "
```
Urlencode the generated cache key to ensure that it only contains valid characters.

Urlencode subscription cache key

---

src/SWP/Bundle/CoreBundle/MessageHandler/ImageConversionHandler.php

Currently, article "updatedAt" is updated when images are successfully converted to webp. The expected behaviour would be to only update the "mediaUpdatedAt" field. This PR fixes #1215.
Call `TimestampableCancelInterface.cancelTimestampable(true)` to cancel the automatic update of "updatedAt" field on article.

Cancel article timestampable when updating mediaUpdatedAt

---

composer.json
src/SWP/Bundle/BridgeBundle/composer.json
src/SWP/Bundle/ContentBundle/composer.json
src/SWP/Bundle/MultiTenancyBundle/composer.json
src/SWP/Bundle/SettingsBundle/composer.json
src/SWP/Bundle/StorageBundle/composer.json
src/SWP/Bundle/UserBundle/composer.json

doctrine/orm 2.13.1 released and gets picked by composer that doesnt work with the sqlite,

Fix SQLite errors

---

src/SWP/Bundle/CoreBundle/Factory/ApiKeyFactory.php

Fix FOSUserBundle legacy code.  FOSUserBundle was remove in [this](https://github.com/superdesk/web-publisher/commit/f007be704b65c1e8fab5cf22c6a4ee93f9d87735) and it's replaced with SWPUserBundle.
Replace  FOS\UserBundle\Model\UserInterface with SWP\Bundle\CoreBundle\Model\UserInterface.

Change FOS user interface with swp user bundle interface

---

src/SWP/Bundle/ContentBundle/Controller/ContentPushController.php
src/SWP/Bundle/CoreBundle/EventSubscriber/ProcessArticleRulesSubscriber.php

Some rules must be processed on article updated/correct
Just trigger all rules, each rule applicator should handle his own execution and check  'isPublished' if necessary. 

Rule processor should process article on update, same as article publish
